/*
 MinPubSub
 a micro publish/subscribe messaging framework
 @see https://github.com/daniellmb/MinPubSub 
 @author Daniel Lamb <daniellmb.com>

 Released under the MIT License
 MelonJS Game Engine
 Copyright (C) 2012, Olivier BIOT
 http://www.melonjs.org

 melonJS is licensed under the MIT License.
 http://www.opensource.org/licenses/mit-license.php

 Tween JS
 https://github.com/sole/Tween.js
*/
var me=me||{};
(function(a){function c(){if(!f){if(!d.body)return setTimeout(c,13);d.removeEventListener?d.removeEventListener("DOMContentLoaded",c,!1):a.removeEventListener("load",c,!1);f=!0;for(var b=0;b<i.length;b++)i[b].call(a,[]);i.length=0}}function b(){return{xmlDoc:null,parseFromString:function(b){a.DOMParser?this.xmlDoc=(new DOMParser).parseFromString(b,"text/xml"):(this.xmlDoc=new ActiveXObject("Microsoft.XMLDOM"),this.xmlDoc.async="false",this.xmlDoc.loadXML(b));null==this.xmlDoc&&console.log("xml "+this.xmlDoc+
" not found!")},getFirstElementByTagName:function(a){return this.xmlDoc?this.xmlDoc.getElementsByTagName(a)[0]:null},getAllTagElements:function(){return this.xmlDoc?this.xmlDoc.getElementsByTagName("*"):null},getStringAttribute:function(a,b,d){return(a=a.getAttribute(b))?a.trim():d},getIntAttribute:function(a,b,d){return(a=this.getStringAttribute(a,b,d))?parseInt(a):d},getFloatAttribute:function(a,b,d){return(a=this.getStringAttribute(a,b,d))?parseFloat(a):d},getBooleanAttribute:function(a,b,d){return(a=
this.getStringAttribute(a,b,d))?"true"==a:d},free:function(){this.xmlDoc=null}}}var d=a.document;me={mod:"melonJS",version:"0.9.5",nocache:"",audio:null,video:null,timer:null,input:null,state:null,game:null,entityPool:null,levelDirector:null,XMLParser:null,loadingScreen:null,TMXTileMap:null};me.sys={ua:navigator.userAgent.toLowerCase(),sound:!1,localStorage:"object"==typeof a.localStorage,gyro:void 0!==a.DeviceMotionEvent,nativeBase64:"function"==typeof a.atob,touch:!1,fps:60,interpolation:!1,scale:null,
gravity:void 0,useNativeAnimFrame:!1,cacheImage:!1,dirtyRegion:!1,stopOnAudioError:!0,pauseOnBlur:!0,preRender:!1,checkVersion:function(a,b){for(var b=b||me.version,d=a.split("."),c=b.split("."),e=Math.min(d.length,c.length),g=0,f=0;f<e&&!(g=+d[f]-+c[f]);f++);return g?g:d.length-c.length}};var e=!1,g=!1,f=!1,i=[];a.onReady=function(b){g||(g=!0,"complete"===d.readyState?c():(d.addEventListener&&d.addEventListener("DOMContentLoaded",c,!1),a.addEventListener("load",c,!1)));f?b.call(a,[]):i.push(function(){return b.call(a,
[])});return this};a.onReady(function(){if(!e){var c=d.createElement("audio");me.utils.setNocache(d.location.href.match(/\?nocache/)||!1);c.canPlayType&&(me.audio.capabilities.mp3="no"!=c.canPlayType("audio/mpeg")&&""!=c.canPlayType("audio/mpeg"),me.audio.capabilities.ogg="no"!=c.canPlayType('audio/ogg; codecs="vorbis"')&&""!=c.canPlayType('audio/ogg; codecs="vorbis"'),me.audio.capabilities.wav="no"!=c.canPlayType('audio/wav; codecs="1"')&&""!=c.canPlayType('audio/wav; codecs="1"'),me.sys.sound=me.audio.capabilities.mp3||
me.audio.capabilities.ogg||me.audio.capabilities.wav);if(-1<me.sys.ua.search("iphone")||-1<me.sys.ua.search("ipod")||-1<me.sys.ua.search("ipad")||-1<me.sys.ua.search("android"))me.sys.sound=!1;me.sys.touch="createTouch"in d||"ontouchstart"in a;me.timer.init();me.XMLParser=new b;me.loadingScreen=new me.DefaultLoadingScreen;me.state.init();me.entityPool.init();me.levelDirector.reset();e=!0}});var m=!1,l=/xyz/.test(function(){})?/\bparent\b/:/.*/;Object.extend=function(a){function b(){!m&&this.init&&
this.init.apply(this,arguments)}var d=this.prototype;m=!0;var c=new this;m=!1;for(var e in a)c[e]="function"==typeof a[e]&&"function"==typeof d[e]&&l.test(a[e])?function(a,b){return function(){var c=this.parent;this.parent=d[a];var e=b.apply(this,arguments);this.parent=c;return e}}(e,a[e]):a[e];b.prototype=c;b.constructor=b;b.extend=Object.extend;return b};"function"!==typeof Object.create&&(Object.create=function(a){function b(){}b.prototype=a;return new b});Function.bind||(Function.prototype.bind=
function(){var a=this,b=Array.prototype.slice.call(arguments),d=b.shift();return function(){return a.apply(d,b.concat(Array.prototype.slice.call(arguments)))}});"undefined"===typeof Date.now&&(Date.now=function(){return(new Date).getTime()});"undefined"===typeof console&&(console={log:function(){},info:function(){},error:function(){alert(Array.prototype.slice.call(arguments).join(", "))}});Function.prototype.defer=function(){var a=this,b=Array.prototype.slice.call(arguments);return window.setTimeout(function(){return a.apply(a,
b)},0.01)};Object.defineProperty||(Object.defineProperty=function(a,b,d){if(a.__defineGetter__)d.get&&a.__defineGetter__(b,d.get),d.set&&a.__defineSetter__(b,d.set);else throw"melonJS: Object.defineProperty not supported";});String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")});String.prototype.isNumeric=function(){return null!=this&&!isNaN(this)&&""!=this.trim()};String.prototype.isBoolean=function(){return null!=this&&("true"==this.trim()||
"false"==this.trim())};String.prototype.contains=function(a){return-1<this.indexOf(a)};String.prototype.toHex=function(){for(var a="",b=0;b<this.length;)a+=this.charCodeAt(b++).toString(16);return a};Number.prototype.clamp=function(a,b){return this<a?a:this>b?b:+this};Number.prototype.random=function(a,b){return~~(Math.random()*(b-a+1))+a};Number.prototype.round=function(){var a=2>arguments.length?this:arguments[0],b=Math.pow(10,arguments[1]||arguments[0]||0);return Math.round(a*b)/b};Number.prototype.toHex=
function(){return"0123456789ABCDEF".charAt(this-this%16>>4)+"0123456789ABCDEF".charAt(this%16)};Number.prototype.sign=function(){return 0>this?-1:0<this?1:0};Number.prototype.degToRad=function(a){return(a||this)/180*Math.PI};Number.prototype.radToDeg=function(a){return(a||this)*(180/Math.PI)};Array.prototype.remove=function(a){a=Array.prototype.indexOf.call(this,a);-1!==a&&Array.prototype.splice.call(this,a,1);return this};Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var d=
0,c=this.length;c--;d++)a.call(b||this,this[d],d,this)});Object.defineProperty(me,"initialized",{get:function(){return e}});var j={},n=[],r,k=[],t=0;j.isDirty=!1;j.reset=function(){n.length=0;k.length=0;r=me.game.viewport.getRect();j.makeAllDirty()};j.makeDirty=function(a,b,d){b&&(j.isDirty=!0,me.sys.dirtyRegion&&(d?n.push(d.union(a)):a.getRect&&n.push(a.getRect())));a.inViewport&&k.unshift(a)};j.makeAllDirty=function(){n.length=0;n.push(r);j.isDirty=!0};j.remove=function(a){var b=k.indexOf(a);-1!=
b&&(k.splice(b,1),a.inViewport=!1,j.makeDirty(a,!0))};j.getDrawCount=function(){return t};j.draw=function(a){var b=me.game.viewport.pos.x,d=me.game.viewport.pos.y;a.save();a.translate(-b,-d);for(var b=b-me.game.currentLevel.pos.x,d=d-me.game.currentLevel.pos.y,c=n.length,e;c--,e=n[c];){for(var g=k.length,f;g--,f=k[g];)if(!me.sys.dirtyRegion||!f.isSprite||f.overlaps(e))!0===f.floating&&(a.save(),a.translate(b,d)),f.draw(a,e),!0===f.floating&&a.restore(),t++;me.debug.renderDirty&&e.draw(a,"white")}a.restore()};
j.flush=function(){me.sys.dirtyRegion&&(n.length=0);k.length=0;j.isDirty=!1;t=0};var w=me,h={},v=null,s=[],A=!1,x=null,u=null,B=function(a,b){return b.z-a.z};h.viewport=null;h.HUD=null;h.collisionMap=null;h.currentLevel=null;h.NO_OBJECT=0;h.ENEMY_OBJECT=1;h.COLLECTABLE_OBJECT=2;h.ACTION_OBJECT=3;h.onLevelLoaded=null;h.init=function(a,b){A||(a=a||me.video.getWidth(),b=b||me.video.getHeight(),h.viewport=new me.Viewport(0,0,a,b),v=me.video.getScreenFrameBuffer(),me.event.publish(me.event.GAME_INIT),
A=!0)};h.reset=function(){A||h.init();h.removeAll();h.viewport&&h.viewport.reset();j.reset();v.setTransform(1,0,0,1,0,0);h.currentLevel={pos:{x:0,y:0}}};h.loadTMXLevel=function(a){h.currentLevel=a;h.collisionMap=h.currentLevel.getLayerByName("collision");(!h.collisionMap||!h.collisionMap.isCollisionMap)&&console.error("WARNING : no collision map detected");for(var b=h.currentLevel.getLayers(),d=b.length;d--;)b[d].visible&&h.add(b[d]);h.viewport.setBounds(Math.max(h.currentLevel.realwidth,h.viewport.width),
Math.max(h.currentLevel.realheight,h.viewport.height));b=h.currentLevel.getObjectGroups();for(d=0;d<b.length;d++)if(b[d].visible)for(var c=0;c<b[d].objects.length;c++)h.addEntity(b[d].objects[c],b[d].z);h.currentLevel.pos.x!=h.currentLevel.pos.y&&v.translate(h.currentLevel.pos.x,h.currentLevel.pos.y);h.sort();h.onLevelLoaded&&h.onLevelLoaded.call(h.onLevelLoaded,a.name);me.event.publish(me.event.LEVEL_LOADED,[a.name])};h.add=function(a,b){a.z=b?b:a.z;s.push(a)};h.addEntity=function(a,b){var d=me.entityPool.newInstanceOf(a);
d&&h.add(d,b)};h.getEntityByName=function(a){for(var b=[],a=a.toLowerCase(),d=s.length,c;d--,c=s[d];)c.name==a&&b.push(c);return b};h.getObjectCount=function(){return s.length};h.getDrawCount=function(){return j.getDrawCount()};h.getEntityByGUID=function(a){for(var b=s.length,d;b--,d=s[b];)if(d.isEntity&&d.GUID==a)return d;return null};h.addHUD=function(a,b,d,c,e){null==h.HUD&&(h.HUD=new me.HUD_Object(a,b,d,c,e),h.add(h.HUD))};h.disableHUD=function(){null!=h.HUD&&(h.remove(h.HUD),h.HUD=null)};h.update=
function(){for(var a=null,b=s.length,d;b--,d=s[b];){var a=me.sys.dirtyRegion&&d.isSprite?d.getRect():null,c=d.update();d.inViewport=d.visible?!d.isSprite||d.floating?!0:h.viewport.isVisible(d):!1;j.makeDirty(d,c,c?a:null)}h.viewport.update(j.isDirty)&&j.makeAllDirty()};h.remove=function(a,b){a.destroy&&a.destroy();j.remove(a);!0===b?s.remove(a):(a.visible=!1,x=function(a){s.remove(a);x=null}.defer(a))};h.removeAll=function(){x&&(clearTimeout(x),x=null);u&&(clearTimeout(u),u=null);for(var a=s.length;a--;)s[a].isPersistent||
h.remove(s[a],!0);j.flush()};h.sort=function(a){null===u&&("function"!==typeof a&&(a=B),u=function(a){s.sort(a);u=null;me.game.repaint()}.defer(a))};h.collide=function(a){for(var b=null,d=s.length,c;(d--,c=s[d])&&(!c.visible||(!c.collidable||!(c.isEntity&&c!=a))||!(b=c.checkCollision(a))););return b};h.repaint=function(){j.makeAllDirty()};h.draw=function(){j.isDirty&&(j.draw(v),h.viewport.draw(v));j.flush()};w.game=h;me.ScreenObject=Object.extend({inViewport:!1,visible:!1,addAsObject:!1,isPersistent:!1,
z:999,rect:null,init:function(a,b){this.isPersistent=(this.addAsObject=this.visible=!0===a||!1)&&!0===b||!1;this.rect=new me.Rect(new me.Vector2d(0,0),0,0)},reset:function(){me.game.reset();this.onResetEvent.apply(this,arguments);this.addAsObject&&(this.visible=!0,this.rect=me.game.viewport.getRect(),me.game.add(this,this.z));me.game.sort()},getRect:function(){return this.rect},destroy:function(){this.onDestroyEvent.apply(this,arguments)},update:function(){return!1},onUpdateFrame:function(){me.timer.update();
me.game.update();me.game.draw();me.video.blitSurface()},draw:function(){},onResetEvent:function(){},onDestroyEvent:function(){}});for(var w=me,M=function(){if(-1==D&&-1==C){me.timer.reset();if(me.sys.useNativeAnimFrame){C=window.requestAnimationFrame(L);if(-1!=C)return;me.sys.useNativeAnimFrame=!1}D=setInterval(H,~~(1E3/me.sys.fps))}},L=function(){H();C=window.requestAnimationFrame(L)},N=function(){-1!=D&&(clearInterval(D),D=-1);-1!=C&&(window.cancelAnimationFrame(C),C=-1)},O=function(a){N();y[z]&&
(y[z].screen.visible&&me.game.remove.call(me.game,y[z].screen,!0),y[z].screen.destroy());y[a]&&(z=a,y[z].screen.reset.apply(y[z].screen,I),H=y[z].screen.onUpdateFrame.bind(y[z].screen),M(),J&&J(),me.game.repaint())},F=["ms","moz","webkit","o"],E=0;E<F.length&&!window.requestAnimationFrame;++E)window.requestAnimationFrame=window[F[E]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[F[E]+"CancelAnimationFrame"]||window[F[E]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=
function(){return-1});window.cancelAnimationFrame||(window.cancelAnimationFrame=function(){return-1});var q={},z=-1,D=-1,C=-1,y={},K="",G=0,J=null,I=null,H=null;q.LOADING=0;q.MENU=1;q.READY=2;q.PLAY=3;q.GAMEOVER=4;q.GAME_END=5;q.SCORE=6;q.CREDITS=7;q.SETTINGS=8;q.USER=100;q.onPause=null;q.onResume=null;q.init=function(){q.set(q.LOADING,me.loadingScreen);a.addEventListener("blur",function(){me.sys.pauseOnBlur&&z!=q.LOADING&&q.pause(!0);if(q.onPause)q.onPause();me.event.publish(me.event.STATE_PAUSE)},
!1);a.addEventListener("focus",function(){me.sys.pauseOnBlur&&z!=q.LOADING&&(q.resume(!0),me.game.repaint());if(q.onResume)q.onResume();me.event.publish(me.event.STATE_RESUME)},!1)};q.pause=function(a){N();a&&me.audio.pauseTrack()};q.resume=function(a){M();a&&me.audio.resumeTrack()};q.isRunning=function(){return-1!=D||-1!=C};q.set=function(a,b){y[a]={};y[a].screen=b;y[a].transition=!0};q.current=function(){return y[z].screen};q.transition=function(a,b,d){"fade"==a&&(K=b,G=d)};q.setTransition=function(a,
b){y[a].transition=b};q.change=function(a){I=null;1<arguments.length&&(I=Array.prototype.slice.call(arguments,1));G&&y[a].transition?(J=function(){me.game.viewport.fadeOut(K,G)},me.game.viewport.fadeIn(K,G,function(){O.defer(a)})):O.defer(a)};q.isCurrent=function(a){return z==a};w.state=q})(window);
(function(a){me.DefaultLoadingScreen=me.ScreenObject.extend({init:function(){this.parent(!0);this.logo1=new me.Font("century gothic",32,"white","middle");this.logo2=new me.Font("century gothic",32,"#89b002","middle");this.logo2.bold();this.invalidate=!1;this.handle=null;this.loadPercent=0},onResetEvent:function(){this.handle=me.event.subscribe(me.event.LOADER_PROGRESS,this.onProgressUpdate.bind(this))},onDestroyEvent:function(){this.logo1=this.logo2=null;this.handle&&(me.event.unsubscribe(this.handle),
this.handle=null)},onProgressUpdate:function(a){this.loadPercent=a;this.invalidate=!0},update:function(){return!0===this.invalidate?(this.invalidate=!1,!0):!1},draw:function(a){var b=this.logo1.measureText(a,"melon").width,d=(a.canvas.width-b-this.logo2.measureText(a,"JS").width)/2,c=a.canvas.height/2;me.video.clearSurface(a,"black");this.logo1.draw(a,"melon",d,c);this.logo2.draw(a,"JS",d+b,c);c+=this.logo1.measureText(a,"melon").height/2;b=Math.floor(this.loadPercent*a.canvas.width);a.strokeStyle=
"silver";a.strokeRect(0,c,a.canvas.width,6);a.fillStyle="#89b002";a.fillRect(2,c+2,b-4,2)}});var c=me,b=function(){if(l==m-n){for(var a in f)if(f[a].isTMX&&me.levelDirector.addTMXLevel(a))e.onResourceLoaded();e.onload?(clearTimeout(j),setTimeout(function(){e.onload();me.event.publish(me.event.LOADER_COMPLETE)},300),n=0):console.error("no load callback defined")}else j=setTimeout(b,100)},d=function(b,d,c){if(a.XMLHttpRequest){var e=new XMLHttpRequest;e.overrideMimeType&&e.overrideMimeType("text/xml")}else e=
new ActiveXObject("Microsoft.XMLHTTP");e.open("GET",b.src+me.nocache,!1);e.onerror=c;e.onload=function(){f[b.name]={xml:e.responseText,isTMX:"tmx"===b.type};d()};e.send()},e={},g={},f={},i={},m=0,l=0,j=0,n=0;e.onload=void 0;e.onProgress=void 0;e.onResourceLoaded=function(){l++;var a=e.getLoadProgress();if(e.onProgress)e.onProgress(a);me.event.publish(me.event.LOADER_PROGRESS,[a])};e.onLoadingError=function(a){throw"melonJS: Failed loading resource "+a.src;};e.preload=function(a){for(var d=0;d<a.length;d++)m+=
e.load(a[d],e.onResourceLoaded.bind(e),e.onLoadingError.bind(e,a[d]));b()};e.load=function(a,b,c){a.name=a.name.toLowerCase();switch(a.type){case "binary":var e=new XMLHttpRequest;e.open("GET",a.src+me.nocache,!1);e.responseType="arraybuffer";xmlhttp.onerror=c;e.onload=function(){var d=e.response;if(d){var d=new Uint8Array(d),c=[];i[a.name]=new dataType;for(var f=0;f<d.byteLength;f++)c[f]=String.fromCharCode(d[f]);i[a.name].data=c.join("");b()}};e.send();return 1;case "image":return g[a.name]=new Image,
g[a.name].onload=b,g[a.name].onerror=c,g[a.name].src=a.src+me.nocache,1;case "tmx":return d.call(this,a,b,c),n+=1,2;case "tsx":return d.call(this,a,b,c),1;case "audio":me.audio.setLoadCallback(b);if(me.audio.isAudioEnable())return me.audio.load(a),1;break;default:throw"melonJS: me.loader.load : unknown or invalid resource type : "+a.type;}return 0};e.unload=function(a){a.name=a.name.toLowerCase();switch(a.type){case "binary":if(!(a.name in i))return!1;delete i[a.name];return!0;case "image":if(!(a.name in
g))return!1;delete g[a.name];return!0;case "tmx":case "tsx":if(!(a.name in f))return!1;delete f[a.name];return!0;case "audio":return me.audio.unload(a.name);default:throw"melonJS: me.loader.unload : unknown or invalid resource type : "+a.type;}};e.unloadAll=function(){for(var a in i)e.unload(a);for(a in g)e.unload(a);for(a in f)e.unload(a);me.audio.unloadAll()};e.getXML=function(a){a=a.toLowerCase();return a in f?f[a].xml:null};e.getBinary=function(a){a=a.toLowerCase();return a in i?i[a]:null};e.getImage=
function(a){a=a.toLowerCase();if(a in g){if(!0===me.sys.cacheImage){var b=me.video.createCanvasSurface(g[a].width,g[a].height);b.drawImage(g[a],0,0);return b.canvas}return g[a]}return null};e.getLoadProgress=function(){return l/m};c.loader=e})(window);
(function(){me.Vector2d=Object.extend({x:0,y:0,init:function(a,c){this.x=a||0;this.y=c||0},set:function(a,c){this.x=a;this.y=c},setZero:function(){this.set(0,0)},setV:function(a){this.x=a.x;this.y=a.y},add:function(a){this.x+=a.x;this.y+=a.y},sub:function(a){this.x-=a.x;this.y-=a.y},scale:function(a){this.x*=a.x;this.y*=a.y},div:function(a){this.x/=a;this.y/=a},abs:function(){0>this.x&&(this.x=-this.x);0>this.y&&(this.y=-this.y)},clamp:function(a,c){return new me.Vector2d(this.x.clamp(a,c),this.y.clamp(a,
c))},clampSelf:function(a,c){this.x=this.x.clamp(a,c);this.y=this.y.clamp(a,c);return this},minV:function(a){this.x=this.x<a.x?this.x:a.x;this.y=this.y<a.y?this.y:a.y},maxV:function(a){this.x=this.x>a.x?this.x:a.x;this.y=this.y>a.y?this.y:a.y},floor:function(){return new me.Vector2d(~~this.x,~~this.y)},floorSelf:function(){this.x=~~this.x;this.y=~~this.y;return this},ceil:function(){return new me.Vector2d(Math.ceil(this.x),Math.ceil(this.y))},ceilSelf:function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);
return this},negate:function(){return new me.Vector2d(-this.x,-this.y)},negateSelf:function(){this.x=-this.x;this.y=-this.y;return this},copy:function(a){this.x=a.x;this.y=a.y},equals:function(a){return this.x===a.x&&this.y===a.y},length:function(){return Math.sqrt(this.x*this.x+this.y*this.y)},normalize:function(){var a=this.length();if(a<Number.MIN_VALUE)return 0;var c=1/a;this.x*=c;this.y*=c;return a},dotProduct:function(a){return this.x*a.x+this.y*a.y},distance:function(a){return Math.sqrt((this.x-
a.x)*(this.x-a.x)+(this.y-a.y)*(this.y-a.y))},clone:function(){return new me.Vector2d(this.x,this.y)},toString:function(){return"x:"+this.x+"y:"+this.y}});me.Rect=Object.extend({pos:null,colPos:null,width:0,height:0,hWidth:0,hHeight:0,init:function(a,c,b){this.pos=a;this.colPos=new me.Vector2d;this.width=c;this.height=b;this.hWidth=~~(c/2);this.hHeight=~~(b/2);Object.defineProperty(this,"left",{get:function(){return this.pos.x},configurable:!0});Object.defineProperty(this,"right",{get:function(){return this.pos.x+
this.width},configurable:!0});Object.defineProperty(this,"top",{get:function(){return this.pos.y},configurable:!0});Object.defineProperty(this,"bottom",{get:function(){return this.pos.y+this.height},configurable:!0})},set:function(a,c,b){this.pos=a;this.width=c;this.height=b;this.hWidth=~~(c/2);this.hHeight=~~(b/2)},getRect:function(){return new me.Rect(this.pos.clone(),this.width,this.height)},union:function(a){var c=Math.min(this.pos.x,a.pos.x),b=Math.min(this.pos.y,a.pos.y);this.width=Math.ceil(Math.max(this.pos.x+
this.width,a.pos.x+a.width)-c);this.height=Math.ceil(Math.max(this.pos.y+this.height,a.pos.y+a.height)-b);this.pos.x=~~c;this.pos.y=~~b;return this},adjustSize:function(a,c,b,d){-1!=a&&(this.colPos.x=a,this.width=c,this.hWidth=~~(this.width/2),this.left!==this.pos.x+this.colPos.x&&Object.defineProperty(this,"left",{get:function(){return this.pos.x+this.colPos.x},configurable:!0}),this.right!==this.pos.x+this.colPos.x+this.width&&Object.defineProperty(this,"right",{get:function(){return this.pos.x+
this.colPos.x+this.width},configurable:!0}));-1!=b&&(this.colPos.y=b,this.height=d,this.hHeight=~~(this.height/2),this.top!==this.pos.y+this.colPos.y&&Object.defineProperty(this,"top",{get:function(){return this.pos.y+this.colPos.y},configurable:!0}),this.bottom!==this.pos.y+this.colPos.y+this.height&&Object.defineProperty(this,"bottom",{get:function(){return this.pos.y+this.colPos.y+this.height},configurable:!0}))},flipX:function(a){this.colPos.x=a-this.width-this.colPos.x;this.hWidth=~~(this.width/
2)},flipY:function(a){this.colPos.y=a-this.height-this.colPos.y;this.hHeight=~~(this.height/2)},overlaps:function(a){return this.left<a.right&&a.left<this.right&&this.top<a.bottom&&a.top<this.bottom},within:function(a){return a.left<=this.left&&a.right>=this.right&&a.top<=this.top&&a.bottom>=this.bottom},contains:function(a){return a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom},containsPoint:function(a){return a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom},
collideVsAABB:function(a){var c=new me.Vector2d(0,0);if(this.overlaps(a)){var b=this.left+this.hWidth-a.left-a.hWidth,d=this.top+this.hHeight-a.top-a.hHeight;c.x=a.hWidth+this.hWidth-(0>b?-b:b);c.y=a.hHeight+this.hHeight-(0>d?-d:d);c.x<c.y?(c.y=0,c.x=0>b?-c.x:c.x):(c.x=0,c.y=0>d?-c.y:c.y)}return c},draw:function(a,c){a.strokeStyle=c||"red";a.strokeRect(this.left,this.top,this.width,this.height)}})})(window);
(function(){me.debug={displayFPS:!1,renderHitBox:!1,renderCollisionMap:!1,renderDirty:!1,renderVelocity:!1,showPanel:function(){var a=me.game.getEntityByName("me.debugPanel")[0];a?a.show():(a=new me.debug.Panel,me.game.add(a),me.game.sort());me.debug.displayFPS=!0}};me.debug.Panel=me.Rect.extend({GUID:null,area:{},z:Infinity,visible:!1,init:function(){this.parent(new me.Vector2d(0,0),me.video.getWidth(),35);this.GUID=me.utils.createGUID();this.name="me.debugPanel";this.floating=this.isPersistent=
!0;this.font=new me.Font("courier",10,"white");this.area.renderHitBox=new me.Rect(new me.Vector2d(160,5),15,15);this.area.renderVelocity=new me.Rect(new me.Vector2d(165,25),15,15);this.area.renderDirty=new me.Rect(new me.Vector2d(270,5),15,15);this.area.renderCollisionMap=new me.Rect(new me.Vector2d(270,25),15,15);this.help_str="(s)how/(h)ide";this.help_str_len=this.font.measureText(me.video.getScreenFrameBuffer(),this.help_str).width;this.fps_str_len=this.font.measureText(me.video.getScreenFrameBuffer(),
"00/00 fps").width;me.input.bindKey(me.input.KEY.S,"show");me.input.bindKey(me.input.KEY.H,"hide");this.samples=[];this.show()},show:function(){this.visible||(this.pos.y=0,me.input.registerMouseEvent("mousedown",this,this.onClick.bind(this)),this.visible=!0,me.game.repaint())},hide:function(){this.visible&&(this.pos.y=-this.height,me.input.releaseMouseEvent("mousedown",this),this.visible=!1,me.game.repaint())},update:function(){me.input.isKeyPressed("show")?this.show():me.input.isKeyPressed("hide")&&
this.hide();return!0},onClick:function(){this.area.renderHitBox.containsPoint(me.input.mouse.pos)?me.debug.renderHitBox=!me.debug.renderHitBox:this.area.renderDirty.containsPoint(me.input.mouse.pos)?me.debug.renderDirty=!me.debug.renderDirty:this.area.renderCollisionMap.containsPoint(me.input.mouse.pos)?me.debug.renderCollisionMap=!me.debug.renderCollisionMap:this.area.renderVelocity.containsPoint(me.input.mouse.pos)&&(me.debug.renderVelocity=!me.debug.renderVelocity);me.game.repaint()},drawMemoryGraph:function(a,
c,b){if(window.performance&&window.performance.memory){var d=Number.prototype.round(window.performance.memory.usedJSHeapSize/1048576,2),e=Number.prototype.round(window.performance.memory.totalJSHeapSize/1048576,2),g=b-c;this.samples.shift();this.samples[g]=25*(d/e);for(var f=g;f--;){var i=b-(g-f);a.beginPath();a.strokeStyle="lightgreen";a.moveTo(i,30);a.lineTo(i,30-(this.samples[f]||0));a.stroke()}this.font.draw(a,d+"/"+e+" MB",c,5)}else this.font.draw(a,"??/?? MB",c,5)},draw:function(a){a.save();
a.globalAlpha=0.5;a.fillStyle="black";a.fillRect(this.left,this.top,this.width,this.height);a.globalAlpha=1;this.font.draw(a,"#objects : "+me.game.getObjectCount(),5,5);this.font.draw(a,"#draws   : "+me.game.getDrawCount(),5,20);this.font.draw(a,"?hitbox   ["+(me.debug.renderHitBox?"x":" ")+"]",100,5);this.font.draw(a,"?velocity ["+(me.debug.renderVelocity?"x":" ")+"]",100,20);this.font.draw(a,"?dirtyRect  ["+(me.debug.renderDirty?"x":" ")+"]",200,5);this.font.draw(a,"?col. layer ["+(me.debug.renderCollisionMap?
"x":" ")+"]",200,20);this.drawMemoryGraph(a,300,this.width-this.help_str_len-15);this.font.draw(a,this.help_str,this.width-this.help_str_len-5,20);this.font.draw(a,""+me.timer.fps+"/"+me.sys.fps+" fps",this.width-this.fps_str_len-5,5);a.restore()},onDestroyEvent:function(){this.hide();me.input.unbindKey(me.input.KEY.S);me.input.unbindKey(me.input.KEY.H)}})})(window);
(function(){var a=Math.min,c=Math.max;me.Viewport=me.Rect.extend({AXIS:{NONE:0,HORIZONTAL:1,VERTICAL:2,BOTH:3},limits:null,target:null,follow_axis:0,_shake:null,_fadeIn:null,_fadeOut:null,_deadwidth:0,_deadheight:0,_limitwidth:0,_limitheight:0,init:function(a,d,c,g,f,i){this.parent(new me.Vector2d(a,d),c-a,g-d);this.limits=new me.Vector2d(f||this.width,i||this.height);this.target=null;this.follow_axis=this.AXIS.NONE;this._shake={intensity:0,duration:0,axis:this.AXIS.BOTH,onComplete:null};this._fadeOut=
{color:0,alpha:0,duration:0,tween:null};this._fadeIn={color:0,alpha:1,duration:0,tween:null};this.setDeadzone(this.width/6,this.height/6)},_followH:function(b){return b.x-this.pos.x>this._deadwidth?(this.pos.x=~~a(b.x-this._deadwidth,this._limitwidth),!0):b.x-this.pos.x<this.deadzone.x?(this.pos.x=~~c(b.x-this.deadzone.x,0),!0):!1},_followV:function(b){return b.y-this.pos.y>this._deadheight?(this.pos.y=~~a(b.y-this._deadheight,this._limitheight),!0):b.y-this.pos.y<this.deadzone.y?(this.pos.y=~~c(b.y-
this.deadzone.y,0),!0):!1},reset:function(a,d){this.pos.x=a||0;this.pos.y=d||0;this.follow_axis=this.target=null},setDeadzone:function(a,d){this.deadzone=new me.Vector2d(~~((this.width-a)/2),~~((this.height-d)/2-0.25*d));this._deadwidth=this.width-this.deadzone.x;this._deadheight=this.height-this.deadzone.y;this.update(!0)},setBounds:function(a,d){this.limits.set(a,d);this._limitwidth=this.limits.x-this.width;this._limitheight=this.limits.y-this.height},follow:function(a,d){if(a instanceof me.ObjectEntity)this.target=
a.pos;else if(a instanceof me.Vector2d)this.target=a;else throw"melonJS: invalid target for viewport.follow";this.follow_axis=d||this.AXIS.BOTH;this.update(!0)},move:function(a,d){var c=~~(this.pos.y+d);this.pos.x=(~~(this.pos.x+a)).clamp(0,this._limitwidth);this.pos.y=c.clamp(0,this._limitheight)},update:function(a){if(this.target&&a)switch(this.follow_axis){case this.AXIS.HORIZONTAL:a=this._followH(this.target);break;case this.AXIS.VERTICAL:a=this._followV(this.target);break;case this.AXIS.BOTH:a=
this._followH(this.target),a=this._followV(this.target)||a}if(0<this._shake.duration)if(this._shake.duration-=me.timer.tick,0>this._shake.duration){if(this._shake.onComplete)this._shake.onComplete()}else{if(this._shake.axis==this.AXIS.BOTH||this._shake.axis==this.AXIS.HORIZONTAL)a=Math.random()*this._shake.intensity,this.pos.x=this.pos.x+this.width+a<this.limits.x?this.pos.x+~~a:this.pos.x-~~a;if(this._shake.axis==this.AXIS.BOTH||this._shake.axis==this.AXIS.VERTICAL)a=Math.random()*this._shake.intensity,
this.pos.y=this.pos.y+this.height+a<this.limits.y?this.pos.y+~~a:this.pos.y-~~a;a=!0}if(null!=this._fadeIn.tween||null!=this._fadeOut.tween)a=!0;return a},shake:function(a,d,c,g){c=c||this.AXIS.BOTH;c==this.AXIS.BOTH&&(this.width==this.limits.x?c=this.AXIS.VERTICAL:this.height==this.limits.y&&(c=this.AXIS.HORIZONTAL));!(c==this.AXIS.HORIZONTAL&&this.width==this.limits.x)&&!(c==this.AXIS.VERTICAL&&this.height==this.limits.y)&&(this._shake.intensity=a,this._shake.duration=d,this._shake.axis=c,this._shake.onComplete=
g||null)},fadeOut:function(a,d,c){this._fadeOut.color=a;this._fadeOut.duration=d||1E3;this._fadeOut.alpha=1;this._fadeOut.tween=(new me.Tween(this._fadeOut)).to({alpha:0},this._fadeOut.duration).onComplete(c||null);this._fadeOut.tween.start()},fadeIn:function(a,d,c){this._fadeIn.color=a;this._fadeIn.duration=d||1E3;this._fadeIn.alpha=0;this._fadeIn.tween=(new me.Tween(this._fadeIn)).to({alpha:1},this._fadeIn.duration).onComplete(c||null);this._fadeIn.tween.start()},getWidth:function(){return this.width},
getHeight:function(){return this.height},focusOn:function(a){this.pos.x=a.x-0.5*this.width;this.pos.y=a.y-0.5*this.height},isVisible:function(a){return a.overlaps(this)},draw:function(a){this._fadeIn.tween&&(a.globalAlpha=this._fadeIn.alpha,me.video.clearSurface(a,me.utils.HexToRGB(this._fadeIn.color)),a.globalAlpha=1,1==this._fadeIn.alpha&&(this._fadeIn.tween=null));this._fadeOut.tween&&(a.globalAlpha=this._fadeOut.alpha,me.video.clearSurface(a,me.utils.HexToRGB(this._fadeOut.color)),a.globalAlpha=
1,0==this._fadeOut.alpha&&(this._fadeOut.tween=null))}})})(window);
(function(){me.SpriteObject=me.Rect.extend({scale:null,scaleFlag:!1,lastflipX:!1,lastflipY:!1,z:0,offset:null,visible:!0,inViewport:!1,angle:0,anchorPoint:null,alpha:1,floating:!1,image:null,flickering:!1,flickerTimer:-1,flickercb:null,flickerState:!1,vp:null,init:function(a,c,b,d,e){this.isSprite=!0;this.parent(new me.Vector2d(a,c),d||b.width,e||b.height);this.image=b;this.scale=new me.Vector2d(1,1);this.offset=new me.Vector2d(0,0);this.anchorPoint=new me.Vector2d(0.5,0.5);this.alpha=1;this.spritecount=
new me.Vector2d(~~(this.image.width/this.width),~~(this.image.height/this.height))},setTransparency:function(a){a="#"==a.charAt(0)?a.substring(1,7):a;this.image=me.video.applyRGBFilter(this.image,"transparent",a.toUpperCase()).canvas},isFlickering:function(){return this.flickering},flicker:function(a,c){this.flickerTimer=a;0>this.flickerTimer?(this.flickering=!1,this.flickercb=null):this.flickering||(this.flickercb=c,this.flickering=!0)},flipX:function(a){a!=this.lastflipX&&(this.lastflipX=a,this.scale.x=
-this.scale.x,this.scaleFlag=1!=this.scale.x||1!=this.scale.y)},flipY:function(a){a!=this.lastflipY&&(this.lastflipY=a,this.scale.y=-this.scale.y,this.scaleFlag=1!=this.scale.x||1!=this.scale.y)},resize:function(a){0<a&&(this.scale.x=0>this.scale.x?-a:a,this.scale.y=0>this.scale.y?-a:a,this.scaleFlag=1!=this.scale.x||1!=this.scale.y)},getOpacity:function(){return this.alpha},setOpacity:function(a){a&&(this.alpha=a.clamp(0,1))},update:function(){return this.flickering?(this.flickerTimer-=me.timer.tick,
0>this.flickerTimer&&(this.flickercb&&this.flickercb(),this.flicker(-1)),!0):!1},draw:function(a){if(this.flickering&&(this.flickerState=!this.flickerState,!this.flickerState))return;a.save();a.globalAlpha=this.alpha;var c=~~this.pos.x,b=~~this.pos.y;if(this.scaleFlag||0!==this.angle){var d=this.width*this.anchorPoint.x,e=this.height*this.anchorPoint.y;a.translate(c+d,b+e);this.scaleFlag&&a.scale(this.scale.x,this.scale.y);0!==this.angle&&a.rotate(this.angle);c=-d;b=-e}a.drawImage(this.image,this.offset.x,
this.offset.y,this.width,this.height,c,b,this.width,this.height);a.restore();me.debug.renderHitBox&&this.parent(a,"blue")},destroy:function(){this.onDestroyEvent.apply(this,arguments)},onDestroyEvent:function(){}});me.AnimationSheet=me.SpriteObject.extend({fpscount:0,animationpause:!1,animationspeed:0,init:function(a,c,b,d,e){this.anim=[];this.current=this.resetAnim=null;this.parent(a,c,b,d,e);1==this.spritecount.x*this.spritecount.y&&(this.setAnimationFrame=function(){});this.animationspeed=me.sys.fps/
10;this.addAnimation("default",null);this.setCurrentAnimation("default")},addAnimation:function(a,c){this.anim[a]={name:a,frame:[],idx:0,length:0};if(null==c)for(var c=[],b=0,d=this.spritecount.x*this.spritecount.y;b<d;b++)c[b]=b;b=0;for(d=c.length;b<d;b++)this.anim[a].frame[b]=new me.Vector2d(this.width*(c[b]%this.spritecount.x),this.height*~~(c[b]/this.spritecount.x));this.anim[a].length=this.anim[a].frame.length},setCurrentAnimation:function(a,c){this.current=this.anim[a];this.resetAnim=c||null;
this.setAnimationFrame(this.current.idx)},isCurrentAnimation:function(a){return this.current.name==a},setAnimationFrame:function(a){this.current.idx=(a||0)%this.current.length;this.offset=this.current.frame[this.current.idx]},update:function(){this.parent();return this.visible&&!this.animationpause&&this.fpscount++>this.animationspeed?(this.setAnimationFrame(++this.current.idx),this.fpscount=0,0==this.current.idx&&this.resetAnim&&("string"==typeof this.resetAnim?this.setCurrentAnimation(this.resetAnim):
"function"==typeof this.resetAnim&&this.resetAnim()),!0):!1}})})(window);
(function(){me.ObjectSettings={name:null,image:null,transparent_color:null,spritewidth:null,spriteheight:null,type:0,collidable:!1};var a=me,c={},b={};c.init=function(){c.add("me.LevelEntity",me.LevelEntity);c.add("me.ObjectEntity",me.ObjectEntity);c.add("me.CollectableEntity",me.CollectableEntity);c.add("me.InvisibleEntity",me.InvisibleEntity)};c.add=function(a,c){b[a.toLowerCase()]=c};c.newInstanceOf=function(a){var c=a.name?a.name.toLowerCase():void 0;if(c&&b[c])return new b[c](a.x,a.y,a);if(a.image)return new me.SpriteObject(a.x,
a.y,a.image);c&&console.error("Cannot instantiate entity of type '"+c+"': Class not found!");return null};a.entityPool=c;me.ObjectEntity=me.AnimationSheet.extend({GUID:null,type:0,collidable:!1,collisionBox:null,init:function(a,b,c){this.parent(a,b,"string"==typeof c.image?me.loader.getImage(c.image):c.image,c.spritewidth,c.spriteheight);c.transparent_color&&this.setTransparency(c.transparent_color);this.GUID=me.utils.createGUID();this.name=c.name?c.name.toLowerCase():"";this.vel=new me.Vector2d;
this.accel=new me.Vector2d;this.friction=new me.Vector2d;this.maxVel=new me.Vector2d(1E3,1E3);this.gravity=void 0!=me.sys.gravity?me.sys.gravity:0.98;this.alive=this.isEntity=!0;this.falling=!1;this.jumping=!0;this.slopeY=0;this.onladder=this.onslope=!1;this.collidable=c.collidable||!1;this.type=c.type||0;this.collisionMap=me.game.collisionMap;this.collisionBox=new me.Rect(this.pos,this.width,this.height);this.canBreakTile=!1;this.onTileBreak=null},updateColRect:function(a,b,c,f){this.collisionBox.adjustSize(a,
b,c,f)},checkCollision:function(a){var b=this.collisionBox.collideVsAABB(a.collisionBox);return 0!=b.x||0!=b.y?(this.onCollision(b,a),b.type=this.type,b.obj=this,b):null},onCollision:function(){this.collidable&&this.type==me.game.COLLECTABLE_OBJECT&&me.game.remove(this)},setVelocity:function(a,b){this.accel.x=0!=a?a:this.accel.x;this.accel.y=0!=b?b:this.accel.y;this.setMaxVelocity(a,b)},setMaxVelocity:function(a,b){this.maxVel.x=a;this.maxVel.y=b},setFriction:function(a,b){this.friction.x=a||0;this.friction.y=
b||0},flipX:function(a){a!=this.lastflipX&&(this.parent(a),this.collisionBox.flipX(this.width))},flipY:function(a){a!=this.lastflipY&&(this.parent(a),this.collisionBox.flipY(this.height))},doWalk:function(a){this.flipX(a);this.vel.x+=a?-this.accel.x*me.timer.tick:this.accel.x*me.timer.tick},doClimb:function(a){return this.onladder?(this.vel.y=a?-this.accel.x*me.timer.tick:this.accel.x*me.timer.tick,!0):!1},doJump:function(){return!this.jumping&&!this.falling?(this.vel.y=-this.maxVel.y*me.timer.tick,
this.jumping=!0):!1},forceJump:function(){this.jumping=this.falling=!1;this.doJump()},distanceTo:function(a){var b=this.pos.x+this.hWidth-(a.pos.x+a.hWidth),a=this.pos.y+this.hHeight-(a.pos.y+a.hHeight);return Math.sqrt(b*b+a*a)},checkSlope:function(a,b){this.pos.y=a.pos.y-this.height;this.slopeY=b?a.height-(this.collisionBox.right+this.vel.x-a.pos.x):this.collisionBox.left+this.vel.x-a.pos.x;this.vel.y=0;this.pos.y+=this.slopeY.clamp(0,a.height)},computeVelocity:function(a){this.gravity&&(a.y+=!this.onladder?
this.gravity*me.timer.tick:0,this.jumping=(this.falling=0<a.y)?!1:this.jumping);this.friction.x&&(a.x=me.utils.applyFriction(a.x,this.friction.x));this.friction.y&&(a.y=me.utils.applyFriction(a.y,this.friction.y));0!=a.y&&(a.y=a.y.clamp(-this.maxVel.y,this.maxVel.y));0!=a.x&&(a.x=a.x.clamp(-this.maxVel.x,this.maxVel.x))},updateMovement:function(){this.computeVelocity(this.vel);var a=this.collisionMap.checkCollision(this.collisionBox,this.vel);this.onslope=a.yprop.isSlope||a.xprop.isSlope;this.onladder=
!1;if(a.y)if(this.onladder=a.yprop.isLadder,0<a.y)if(a.yprop.isSolid||a.yprop.isPlatform&&this.collisionBox.bottom-1<=a.ytile.pos.y)this.pos.y=~~this.pos.y,this.vel.y=this.falling?a.ytile.pos.y-this.collisionBox.bottom:0,this.falling=!1;else if(a.yprop.isSlope&&!this.jumping)this.checkSlope(a.ytile,a.yprop.isLeftSlope),this.falling=!1;else{if(a.yprop.isBreakable)if(this.canBreakTile){if(me.game.currentLevel.clearTile(a.ytile.col,a.ytile.row),this.onTileBreak)this.onTileBreak()}else this.pos.y=~~this.pos.y,
this.vel.y=this.falling?a.ytile.pos.y-this.collisionBox.bottom:0,this.falling=!1}else 0>a.y&&(!a.yprop.isPlatform&&!a.yprop.isLadder)&&(this.falling=!0,this.vel.y=0);if(a.x)if(this.onladder=a.xprop.isLadder,a.xprop.isSlope&&!this.jumping)this.checkSlope(a.xtile,a.xprop.isLeftSlope),this.falling=!1;else if(!a.xprop.isPlatform&&!a.xprop.isLadder)if(a.xprop.isBreakable&&this.canBreakTile){if(me.game.currentLevel.clearTile(a.xtile.col,a.xtile.row),this.onTileBreak)this.onTileBreak()}else this.vel.x=0;
this.pos.add(this.vel);return a},draw:function(a){this.parent(a);if(me.debug.renderHitBox){this.collisionBox.draw(a,"red");var b=~~(this.pos.x+this.hWidth),c=~~(this.pos.y+this.hHeight);a.lineWidth=1;a.beginPath();a.moveTo(b,c);a.lineTo(b+~~(this.vel.x*this.hWidth),c+~~(this.vel.y*this.hHeight));a.stroke()}}});me.CollectableEntity=me.ObjectEntity.extend({init:function(a,b,c){this.parent(a,b,c);this.collidable=!0;this.type=me.game.COLLECTABLE_OBJECT}});me.InvisibleEntity=me.Rect.extend({GUID:null,
z:0,collisionBox:null,init:function(a,b,c){this.parent(new me.Vector2d(a,b),c.width,c.height);this.collisionBox=new me.Rect(this.pos,c.width,c.height);this.GUID=me.utils.createGUID();this.name=c.name?c.name.toLowerCase():"";this.isEntity=this.collidable=this.visible=!0},updateColRect:function(a,b,c,f){this.collisionBox.adjustSize(a,b,c,f)},checkCollision:function(a){var b=this.collisionBox.collideVsAABB(a.collisionBox);return 0!=b.x||0!=b.y?(this.onCollision(b,a),b.type=this.type,b.obj=this,b):null},
onCollision:function(){},destroy:function(){this.onDestroyEvent.apply(this,arguments)},onDestroyEvent:function(){},update:function(){return!1},draw:function(a){me.debug.renderHitBox&&(a.strokeStyle="blue",a.strokeRect(this.pos.x,this.pos.y,this.width,this.height),this.collisionBox.draw(a))}});me.LevelEntity=me.InvisibleEntity.extend({init:function(a,b,c){this.parent(a,b,c);this.nextlevel=c.to;this.fade=c.fade;this.duration=c.duration;this.fading=!1;this.gotolevel=c.to},onFadeComplete:function(){me.levelDirector.loadLevel(this.gotolevel);
me.game.viewport.fadeOut(this.fade,this.duration)},goTo:function(a){this.gotolevel=a||this.nextlevel;this.fade&&this.duration?this.fading||(this.fading=!0,me.game.viewport.fadeIn(this.fade,this.duration,this.onFadeComplete.bind(this))):me.levelDirector.loadLevel(this.gotolevel)},onCollision:function(){this.goTo()}})})(window);
(function(){me.Font=Object.extend({ALIGN:{LEFT:"left",CENTER:"center",RIGHT:"right"},font:null,height:null,color:null,align:null,init:function(a,c,b,d){this.set(a,c,b,d)},bold:function(){this.font="bold "+this.font},italic:function(){this.font="italic "+this.font},set:function(a,c,b,d){this.font=""+c+"px '"+a+"'";this.height=c;this.color=b;this.align=d||"top"},getRect:function(){return new me.Rect(new Vector2d(0,0),0,0)},measureText:function(a,c){a.font=this.font;a.fillStyle=this.color;a.textBaseline=
this.align;var b=a.measureText(c);b.height=this.height;return b},draw:function(a,c,b,d){a.font=this.font;a.fillStyle=this.color;a.textBaseline=this.align;a.fillText(c,~~b,~~d)}});me.BitmapFont=me.Font.extend({size:null,sSize:null,firstChar:32,charCount:0,init:function(a,c,b,d){this.parent(a,null,null);this.size=new me.Vector2d;this.sSize=new me.Vector2d;this.firstChar=d||32;this.loadFontMetrics(a,c);this.align=this.ALIGN.RIGHT;b&&this.resize(b)},loadFontMetrics:function(a,c){this.font=me.loader.getImage(a);
this.size.x=c.x||c;this.size.y=c.y||this.font.height;this.sSize.copy(this.size);this.charCount=~~(this.font.width/this.size.x)},set:function(a,c){this.align=a;c&&this.resize(c)},resize:function(a){this.sSize.copy(this.size);this.sSize.x*=a;this.sSize.y*=a},measureText:function(a){return{width:a.length*this.sSize.x,height:this.sSize.y}},draw:function(a,c,b,d){c=new String(c);switch(this.align){case this.ALIGN.RIGHT:b-=this.measureText(c).width;break;case this.ALIGN.CENTER:b-=0.5*this.measureText(c).width}for(var e=
0,g=c.length;e<g;e++){var f=c.charCodeAt(e)-this.firstChar;a.drawImage(this.font,this.size.x*(f%this.charCount),this.size.y*~~(f/this.charCount),this.size.x,this.size.y,~~b,~~d,this.sSize.x,this.sSize.y);b+=this.sSize.x}}})})(window);
(function(){me.GUI_Object=me.SpriteObject.extend({isClickable:!0,updated:!1,init:function(a,c,b){this.parent(a,c,"string"==typeof b.image?me.loader.getImage(b.image):b.image,b.spritewidth,b.spriteheight);this.floating=!0;me.input.registerMouseEvent("mousedown",this,this.clicked.bind(this))},update:function(){return this.updated?(this.updated=!1,!0):!1},clicked:function(){if(this.isClickable)return this.updated=!0,this.onClick()},onClick:function(){return!0},onDestroyEvent:function(){me.input.releaseMouseEvent("mousedown",
this)}})})(window);
(function(){me.HUD_Item=Object.extend({init:function(a,c,b){this.pos=new me.Vector2d(a||0,c||0);this.visible=!0;this.defaultvalue=b||0;this.value=b||0;this.updated=!0},reset:function(){this.set(this.defaultvalue)},set:function(a){this.value=a;return this.updated=!0},update:function(a){return this.set(this.value+a)},draw:function(){}});me.HUD_Object=me.Rect.extend({init:function(a,c,b,d,e){this.parent(new me.Vector2d(a||0,c||0),b||me.video.getWidth(),d||me.video.getHeight());this.bgcolor=e;this.HUDItems=
{};this.HUDobj=[];this.objCount=0;this.HUD_invalidated=this.floating=this.visible=!0;this.HUDCanvasSurface=me.video.createCanvasSurface(this.width,this.height);this.z=999;this.isPersistent=!0},addItem:function(a,c){this.HUDItems[a]=c;this.HUDobj.push(this.HUDItems[a]);this.objCount++;this.HUD_invalidated=!0},removeItem:function(a){this.HUDItems[a]&&(this.HUDobj.splice(this.HUDobj.indexOf(this.HUDItems[a]),1),this.HUDItems[a]=null,this.objCount--,this.HUD_invalidated=!0)},setItemValue:function(a,c){this.HUDItems[a]&&
!0==this.HUDItems[a].set(c)&&(this.HUD_invalidated=!0)},updateItemValue:function(a,c){this.HUDItems[a]&&!0==this.HUDItems[a].update(c)&&(this.HUD_invalidated=!0)},getItemValue:function(a){return this.HUDItems[a]?this.HUDItems[a].value:0},update:function(){return this.HUD_invalidated},reset:function(a){void 0!=a?(this.HUDItems[a]&&this.HUDItems[a].reset(),this.HUD_invalidated=!0):this.resetAll()},resetAll:function(){for(var a=this.objCount,c;a--,c=this.HUDobj[a];)c.reset();this.HUD_invalidated=!0},
getRect:function(){p=this.pos.clone();p.add(me.game.viewport.pos);return new me.Rect(p,this.width,this.height)},draw:function(a){if(this.HUD_invalidated){this.bgcolor?me.video.clearSurface(this.HUDCanvasSurface,this.bgcolor):this.HUDCanvasSurface.canvas.width=this.HUDCanvasSurface.canvas.width;for(var c=this.objCount,b;c--,b=this.HUDobj[c];)b.visible&&(b.draw(this.HUDCanvasSurface,0,0),b.updated&&(b.updated=!1))}a.drawImage(this.HUDCanvasSurface.canvas,this.pos.x,this.pos.y);this.HUD_invalidated=
!1}})})(window);
(function(){var a=me,c=function(a){for(var a=g[a],b=0,c;c=a[b++];)if(c.ended||!c.currentTime)return c.currentTime=k,c;a[0].pause();a[0].currentTime=k;return a[0]},b=function(a,b,d){var e=c(a.toLowerCase());e.loop=b||!1;e.play();d&&!b&&e.addEventListener("ended",function(a){e.removeEventListener("ended",arguments.callee,!1);d()},!1)},d=function(a,b,c){c&&!b&&setTimeout(c,2E3)},e={},g={},f=["mp3","ogg","wav"],i=null,m=-1,l=null,j=null,n=null,r=!0,k=0,t=0;e.capabilities={mp3:!1,ogg:!1,ma4:!1,wav:!1};
e.init=function(a){if(!me.initialized)return console.error("melonJS: me.audio.init() called before engine initialization."),!1;i=a?new String(a):new String("mp3");var c=a="",g=null,l=0,j=f.length;if(me.sys.sound)for(;l<j;l++)if(c=f[l],g=RegExp(c,"i"),-1!=i.search(g)&&e.capabilities[c]){a=c;break}""===a&&(r=!1);m=a;e.play=r?b:d;return r};e.setLoadCallback=function(a){l=a};e.isAudioEnable=function(){return r};e.enable=function(){r=me.sys.sound;e.play=r?b:d};e.disable=function(){r=!1;e.play=d};e.load=
function(a){if(-1==m)return 0;var b=new Audio(a.src+a.name+"."+m+me.nocache);b.preload="auto";b.addEventListener("canplaythrough",function(b){this.removeEventListener("canplaythrough",arguments.callee,!1);var c=a.name,d=a.channel;t=0;if(1<d)for(var e=g[c][0],f=1;f<d;f++){var j=e.cloneNode(!0);0==j.currentSrc.length&&(j.src=e.src);g[c][f]=j;g[c][f].load()}l&&l()},!1);b.addEventListener("error",function(){var b=a.name;if(3<t++)if(b="melonJS: failed loading "+b+"."+m,!1===me.sys.stopOnAudioError)me.audio.disable(),
l&&l(),console.log(b+", disabling audio");else throw b;else g[b][0].load()},!1);b.src=a.src+a.name+"."+m+me.nocache;b.load();g[a.name]=[b];return 1};e.stop=function(a){if(r)for(var a=g[a.toLowerCase()],b=a.length;b--;)a[b].pause(),a[b].currentTime=k};e.pause=function(a){if(r)for(var a=g[a.toLowerCase()],b=a.length;b--;)a[b].pause()};e.playTrack=function(a){if(r&&(null!=n&&e.stopTrack(),a=a.toLowerCase(),n=c(a)))j=a,n.loop=!0,n.play()};e.stopTrack=function(){r&&n&&(n.pause(),n=j=null)};e.pauseTrack=
function(){r&&n&&n.pause()};e.resumeTrack=function(){r&&n&&n.play()};e.unload=function(a){a=a.toLowerCase();if(!(a in g))return!1;j===a?e.stopTrack():e.stop(a);delete g[a];return!0};e.unloadAll=function(){for(var a in g)e.unload(a)};a.audio=e})(window);
(function(){var a=me,c={},b=null,d=0,e=0,g=0,f=0,i=0,m=Math.ceil(1E3/me.sys.fps),l=1.25*(1E3/me.sys.fps);c.tick=1;c.fps=0;c.init=function(){b=document.getElementById("framecounter");null!==b&&(me.debug.displayFPS=!0);c.reset()};c.reset=function(){f=g=Date.now();d=e=0};c.getTime=function(){return f};c.update=function(){g=f;f=Date.now();i=f-g;me.debug.displayFPS&&(d++,e+=i,0==d%10&&(this.fps=(~~(1E3*d/e)).clamp(0,me.sys.fps),d=e=0),null!==b&&b.replaceChild(document.createTextNode("("+this.fps+"/"+me.sys.fps+
" fps)"),b.firstChild));c.tick=i>l&&me.sys.interpolation?i/m:1};a.timer=c;var a=me,j={},n=null,r=null,k=null,t=null,w=null,h=-1,v=!1,s=0,A=0,x=!1,u=!0;j.init=function(a,b,c,d,e,f){if(!me.initialized)throw"melonJS: me.video.init() called before engine initialization.";v=d||!1;x="auto"===e||!1;u=void 0!==f?f:!0;e="auto"!==e?parseFloat(e||1):1;me.sys.scale=new me.Vector2d(e,e);if(x||1!==e)v=!0;s=b*me.sys.scale.x;A=c*me.sys.scale.y;window.addEventListener("resize",function(a){me.event.publish(me.event.WINDOW_ONRESIZE,
[a])},!1);window.addEventListener("orientationchange",function(a){me.event.publish(me.event.WINDOW_ONRESIZE,[a])},!1);me.event.subscribe(me.event.WINDOW_ONRESIZE,me.video.onresize.bind(me.video));n=document.createElement("canvas");n.setAttribute("width",s+"px");n.setAttribute("height",A+"px");n.setAttribute("border","0px solid black");n.setAttribute("display","block");w=a?document.getElementById(a):document.body;w.appendChild(n);if(!n.getContext)return!1;r=n.getContext("2d");v?(t=j.createCanvasSurface(b,
c),k=t.canvas):(t=r,k=r.canvas);if(x)me.video.onresize(null);return!0};j.getWrapper=function(){return w};j.getWidth=function(){return k.width};j.getPos=function(a){for(var a=a||n,b=new me.Vector2d(a.offsetLeft,a.offsetTop);a=a.offsetParent;)b.x+=a.offsetLeft,b.y+=a.offsetTop;return b};j.getHeight=function(){return k.height};j.createCanvasSurface=function(a,b){var c=document.createElement("canvas");c.width=a||k.width;c.height=b||k.height;return c.getContext("2d")};j.getScreenCanvas=function(){return n};
j.getScreenFrameBuffer=function(){return t};j.onresize=function(){if(x){var a=me.video.getScreenCanvas().parentNode,b=a.width||window.innerWidth,a=a.height||window.innerHeight;h&&clearTimeout(h);if(u){var c=me.video.getWidth()/me.video.getHeight(),b=b/a<c?b/me.video.getWidth():a/me.video.getHeight();h=me.video.updateDisplaySize.defer(b,b)}else h=me.video.updateDisplaySize.defer(b/me.video.getWidth(),a/me.video.getHeight())}else me.input.mouse.offset=me.video.getPos()};j.updateDisplaySize=function(a,
b){me.sys.scale.set(a,b);n.width=s=k.width*a;n.height=A=k.height*b;me.input.mouse.offset=me.video.getPos();j.blitSurface();h=-1};j.clearSurface=function(a,b){a.save();a.setTransform(1,0,0,1,0,0);a.fillStyle=b;a.fillRect(0,0,a.canvas.width,a.canvas.height);a.restore()};j.scale=function(a,b){a.translate(-(a.canvas.width*b-a.canvas.width>>1),-(a.canvas.height*b-a.canvas.height>>1));a.scale(b,b)};j.setAlpha=function(a,b){a.globalCompositeOperation=b?"source-over":"copy"};j.blitSurface=function(){j.blitSurface=
v?function(){r.drawImage(k,0,0,k.width,k.height,0,0,s,A)}:function(){};j.blitSurface()};j.applyRGBFilter=function(a,b,c){var d=j.createCanvasSurface(a.width,a.height),a=me.utils.getPixels(a),e=a.data;switch(b){case "b&w":for(var b=0,f=e.length;b<f;b+=4)c=3*e[b]+4*e[b+1]+e[b+2]>>>3,e[b]=c,e[b+1]=c,e[b+2]=c;break;case "brightness":c=Math.abs(c).clamp(0,1);b=0;for(f=e.length;b<f;b+=4)e[b]*=c,e[b+1]*=c,e[b+2]*=c;break;case "transparent":b=0;for(f=e.length;b<f;b+=4)me.utils.RGBToHex(e[b],e[b+1],e[b+2])===
c&&(e[b+3]=0);break;default:return null}d.putImageData(a,0,0);return d};a.video=j})(window);
(function(a){var c=me,b=function(){if(!A){k.touches.push({x:0,y:0});k.mouse.pos=new me.Vector2d(0,0);k.mouse.offset=me.video.getPos();if(me.sys.touch){me.video.getScreenCanvas().addEventListener("touchmove",l,!1);for(var b=2;b<B.length;++b)me.video.getScreenCanvas().addEventListener(B[b],n,!1)}else{me.video.getScreenCanvas().addEventListener("mousemove",l,!1);a.addEventListener("mousewheel",m,!1);for(b=2;b<u.length;++b)me.video.getScreenCanvas().addEventListener(u[b],j,!1)}A=!0}},d=function(a){a.stopPropagation?
a.stopPropagation():a.cancelBubble=!0;a.preventDefault?a.preventDefault():a.returnValue=!1;return!1},e=function(a,b){var c=t[b||a.keyCode||a.which];return c?(v[c]||(w[c]=!0,v[c]=h[c],me.event.publish(me.event.KEYDOWN,[c])),d(a)):!0},g=function(a,b){var c=t[b||a.keyCode||a.which];return c?(w[c]=!1,v[c]=!1,me.event.publish(me.event.KEYUP,[c]),d(a)):!0},f=function(a){var b=!1,c=k.mouse.handlers[a.type];if(c)for(var d=me.game.viewport.pos,e=me.game.currentLevel.pos,f=0,g=k.touches.length;f<g;f++)for(var l=
k.touches[f].x,j=k.touches[f].y,h=c.length,i;h--,i=c[h];){var r=!1===i.floating?{x:l+d.x-e.x,y:j+d.y-e.y}:{x:l,y:j};if((null===i.rect||i.rect.containsPoint(r))&&!1===i.cb(a)){b=!0;break}}return b},i=function(a){k.touches.length=0;if(a.touches)for(var b=k.mouse.offset,c=0,d=a.changedTouches.length;c<d;c++){var e=a.changedTouches[c],f=e.clientX-b.x,g=e.clientY-b.y,l=me.sys.scale;if(1!=l.x||1!=l.y)f/=l.x,g/=l.y;k.touches.push({x:f,y:g,id:e.identifier})}else{var b=k.mouse.offset,f=a.pageX-b.x,g=a.pageY-
b.y,l=me.sys.scale;if(1!=l.x||1!=l.y)f/=l.x,g/=l.y;k.touches.push({x:f,y:g,id:0})}k.mouse.pos.set(k.touches[0].x,k.touches[0].y)},m=function(a){return a.target==me.video.getScreenCanvas()&&f(a)?d(a):!0},l=function(a){i(a);return f(a)?d(a):!0},j=function(a){if(f(a))return d(a);var b=k.mouse.bind[a.button||0];return b?"mousedown"===a.type||"touchstart"===a.type?e(a,b):g(a,b):!0},n=function(a){i(a);return j(a)},r=function(a){k.accel=a.accelerationIncludingGravity},k={},t={},w={},h={},v={},s=!1,A=!1,
x=!1,u="mousewheel mousemove mousedown mouseup click dblclick".split(" "),B=[void 0,"touchmove","touchstart","touchend","tap","dbltap"];k.accel={x:0,y:0,z:0};k.mouse={pos:null,offset:null,LEFT:0,MIDDLE:1,RIGHT:2,bind:[0,0,0],handlers:{}};k.touches=[];k.KEY={LEFT:37,UP:38,RIGHT:39,DOWN:40,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,ESC:27,SPACE:32,NUM0:48,NUM1:49,NUM2:50,NUM3:51,NUM4:52,NUM5:53,NUM6:54,NUM7:55,NUM8:56,NUM9:57,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,
P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90};k.isKeyPressed=function(a){return w[a]?(h[a]&&(v[a]=!0,w[a]=!1),!0):!1};k.keyStatus=function(a){return!0===v[a]?!0:w[a]};k.triggerKeyEvent=function(a,b){b?e({},a):g({},a)};k.bindKey=function(b,c,d){s||(a.addEventListener("keydown",e,!1),a.addEventListener("keyup",g,!1),s=!0);t[b]=c;w[c]=!1;h[c]=d?d:!1;v[c]=!1};k.unbindKey=function(a){w[t[a]]=!1;h[t[a]]=!1;t[a]=null};k.bindMouse=function(a,c){b();if(!t[c])throw"melonJS : no action defined for keycode "+
c;k.mouse.bind[a]=c};k.unbindMouse=function(a){k.mouse.bind[a]=null};k.bindTouch=function(a){k.bindMouse(me.input.mouse.LEFT,a)};k.unbindTouch=function(){k.unbindMouse(me.input.mouse.LEFT)};k.registerMouseEvent=function(a,c,d,e){b();me.sys.touch&&-1!==u.indexOf(a)&&(a=B[u.indexOf(a)]);if(a&&(-1!==u.indexOf(a)||-1!==B.indexOf(a))){k.mouse.handlers[a]||(k.mouse.handlers[a]=[]);var f=!0===c.floating?!0:!1;e&&(f=!0===e?!0:!1);k.mouse.handlers[a].push({rect:c||null,cb:d,floating:f})}else throw"melonJS : invalid event type : "+
a;};k.releaseMouseEvent=function(a,b){me.sys.touch&&-1!==u.indexOf(a)&&(a=B[u.indexOf(a)]);if(a&&(-1!==u.indexOf(a)||-1!==B.indexOf(a))){k.mouse.handlers[a]||(k.mouse.handlers[a]=[]);var c=k.mouse.handlers[a];if(c)for(var d=c.length,e;d--,e=c[d];)e.rect===b&&(e.rect=e.cb=e.floating=null,k.mouse.handlers[a].splice(d,1))}else throw"melonJS : invalid event type : "+a;};k.watchAccelerometer=function(){return a.sys.gyro?(x||(a.addEventListener("devicemotion",r,!1),x=!0),!0):!1};k.unwatchAccelerometer=
function(){x&&(a.removeEventListener("devicemotion",r,!1),x=!1)};c.input=k})(window);
(function(a){var c={decode:function(b){b=b.replace(/[^A-Za-z0-9\+\/\=]/g,"");if(me.sys.nativeBase64)return a.atob(b);for(var c=[],d,e,f,g,i,h=0;h<b.length;)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(h++)),e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(h++)),g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(h++)),i="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(h++)),
d=d<<2|e>>4,e=(e&15)<<4|g>>2,f=(g&3)<<6|i,c.push(String.fromCharCode(d)),64!=g&&c.push(String.fromCharCode(e)),64!=i&&c.push(String.fromCharCode(f));return c=c.join("")}},b=me,d={},e={},g="",f=0,i=/^.*(\\|\/|\:)/,m=/\.[^\.]*$/;d.decodeBase64=function(a){return c.decode(a)};d.decodeBase64AsArray=function(a,b){var b=b||1,d=c.decode(a),e=[],f,g,i;f=0;for(i=d.length/b;f<i;f++){e[f]=0;for(g=b-1;0<=g;--g)e[f]+=d.charCodeAt(f*b+g)<<(g<<3)}return e};d.decodeCSV=function(a,b){for(var a=a.trim().split("\n"),
c=[],d=0;d<a.length;d++){entries=a[d].split(",",b);for(var e=0;e<entries.length;e++)c.push(+entries[e])}return c};d.getBasename=function(a){return a.replace(i,"").replace(m,"")};d.setNocache=function(a){me.nocache=a?"?"+parseInt(1E7*Math.random()):""};d.HexToRGB=function(a,b){if("#"!==a.charAt(0))return a;a=a.substring(1,a.length);if(null==e[a]){if(6>a.length)var c=a.charAt(0)+a.charAt(0),d=a.charAt(1)+a.charAt(1),f=a.charAt(2)+a.charAt(2);else c=a.substring(0,2),d=a.substring(2,4),f=a.substring(4,
6);e[a]=parseInt(c,16)+","+parseInt(d,16)+","+parseInt(f,16)}return(b?"rgba(":"rgb(")+e[a]+(b?","+b+")":")")};d.RGBToHex=function(a,b,c){return a.toHex()+b.toHex()+c.toHex()};d.getPixels=function(a){if(a instanceof HTMLImageElement){var b=me.video.createCanvasSurface(a.width,a.height);b.drawImage(a,0,0);return b.getImageData(0,0,a.width,a.height)}return a.getContext("2d").getImageData(0,0,a.width,a.height)};d.resetGUID=function(a){g=a.toString().toUpperCase().toHex();f=0};d.createGUID=function(){return g+
"-"+f++};d.applyFriction=function(a,b){return 0>a+b?a+b*me.timer.tick:0<a-b?a-b*me.timer.tick:0};b.utils=d})(window);
(function(){function a(a){this.defaultvalue=a||0;this.value=a||0;this.updated=!0}a.prototype.reset=function(){this.set(this.defaultvalue)};a.prototype.update=function(a){return this.set(this.value+a)};a.prototype.set=function(a){this.value=a;return this.updated=!0};var c=me,b={},d={},e=[],g=0;b.add=function(b,c){if(b.constructor===Object)for(var m in b){var l=m;d[l]=new a(b[m]);e.push(d[l]);g++}else d[b]=new a(c),e.push(d[b]),g++};b.updateValue=function(a,b){if(a.constructor===Object)for(var c in a)d[c]&&
d[c].update(a[c]);else d[a]&&d[a].update(b)};b.setValue=function(a,b){if(a.constructor===Object)for(var c in a)d[c]&&d[c].set(a[c]);else d[a]&&d[a].set(b)};b.getItemValue=function(a){return d[a]?d[a].value:0};b.reset=function(a){void 0!=a?d[a]&&d[a].reset():b.resetAll()};b.resetAll=function(){for(var a=g,b;a--,b=e[a];)b.reset()};c.gamestat=b})(window);
(function(){me.LevelConstants={COLLISION_MAP:"collision",PARALLAX_MAP:"parallax"};me.TMX_TAG_MAP="map";me.TMX_TAG_NAME="name";me.TMX_TAG_VALUE="value";me.TMX_TAG_VERSION="version";me.TMX_TAG_ORIENTATION="orientation";me.TMX_TAG_WIDTH="width";me.TMX_TAG_HEIGHT="height";me.TMX_TAG_OPACITY="opacity";me.TMX_TAG_TRANS="trans";me.TMX_TAG_TILEWIDTH="tilewidth";me.TMX_TAG_TILEHEIGHT="tileheight";me.TMX_TAG_TILEOFFSET="tileoffset";me.TMX_TAG_FIRSTGID="firstgid";me.TMX_TAG_GID="gid";me.TMX_TAG_TILE="tile";
me.TMX_TAG_ID="id";me.TMX_TAG_DATA="data";me.TMX_TAG_COMPRESSION="compression";me.TMX_TAG_ENCODING="encoding";me.TMX_TAG_ATTR_BASE64="base64";me.TMX_TAG_CSV="csv";me.TMX_TAG_SPACING="spacing";me.TMX_TAG_MARGIN="margin";me.TMX_TAG_PROPERTIES="properties";me.TMX_TAG_PROPERTY="property";me.TMX_TAG_IMAGE="image";me.TMX_TAG_SOURCE="source";me.TMX_TAG_VISIBLE="visible";me.TMX_TAG_TILESET="tileset";me.TMX_TAG_LAYER="layer";me.TMX_TAG_IMAGE_LAYER="imagelayer";me.TMX_TAG_OBJECTGROUP="objectgroup";me.TMX_TAG_OBJECT=
"object";me.TMX_TAG_X="x";me.TMX_TAG_Y="y";me.TMX_TAG_WIDTH="width";me.TMX_TAG_HEIGHT="height";me.TMX_TAG_POLYGON="polygon";me.TMX_TAG_POLYLINE="polyline";me.TMX_TAG_POINTS="points";me.TMX_BACKGROUND_COLOR="backgroundcolor"})(window);
(function(){me.TMXUtils={setTMXProperties:function(a,c){var b=c.getElementsByTagName(me.TMX_TAG_PROPERTIES)[0];if(b)for(var b=b.getElementsByTagName(me.TMX_TAG_PROPERTY),d=0;d<b.length;d++){var e=me.XMLParser.getStringAttribute(b[d],me.TMX_TAG_NAME),g=me.XMLParser.getStringAttribute(b[d],me.TMX_TAG_VALUE);!g||g.isBoolean()?g=g?"true"==g:!0:g.isNumeric()&&(g=Number(g));a[e]=g}},mergeProperties:function(a,c,b){for(var d in c)if(b||void 0===a[d])a[d]=c[d];return a}}})(window);
(function(){me.TMXOBjectGroup=Object.extend({init:function(a,c,b,d){this.objects=[];this.name=a;this.width=me.XMLParser.getIntAttribute(c,me.TMX_TAG_WIDTH);this.height=me.XMLParser.getIntAttribute(c,me.TMX_TAG_HEIGHT);this.visible=1==me.XMLParser.getIntAttribute(c,me.TMX_TAG_VISIBLE,1);this.z=d;c.firstChild&&c.firstChild.nextSibling.nodeName===me.TMX_TAG_PROPERTIES&&me.TMXUtils.setTMXProperties(this,c);a=c.getElementsByTagName(me.TMX_TAG_OBJECT);for(c=0;c<a.length;c++)this.objects.push(new me.TMXOBject(a[c],
b,d))},reset:function(){this.objects=null},getObjectCount:function(){return this.objects.length},getObjectByIndex:function(a){return this.objects[a]}});me.TMXOBject=Object.extend({init:function(a,c,b){this.name=me.XMLParser.getStringAttribute(a,me.TMX_TAG_NAME);this.x=me.XMLParser.getIntAttribute(a,me.TMX_TAG_X);this.y=me.XMLParser.getIntAttribute(a,me.TMX_TAG_Y);this.z=b;this.width=me.XMLParser.getIntAttribute(a,me.TMX_TAG_WIDTH,0);this.height=me.XMLParser.getIntAttribute(a,me.TMX_TAG_HEIGHT,0);
if(this.gid=me.XMLParser.getIntAttribute(a,me.TMX_TAG_GID,null))c=c.getTilesetByGid(this.gid),this.width=c.tilewidth,this.height=c.tileheight,this.spritewidth=this.width,this.y-=this.height,b=new me.Tile(this.x,this.y,c.tilewidth,c.tileheight,this.gid),this.image=c.getTileImage(b);else if(c=a.getElementsByTagName(me.TMX_TAG_POLYGON),this.isPolygon=!0,c.length||(c=a.getElementsByTagName(me.TMX_TAG_POLYLINE),this.isPolygon=!1),c.length){this.points=[];for(var c=me.XMLParser.getStringAttribute(c[0],
me.TMX_TAG_POINTS).split(" "),b=0,d;b<c.length;b++)d=c[b].split(","),this.points[b]=new me.Vector2d(+d[0],+d[1])}me.TMXUtils.setTMXProperties(this,a)},getObjectPropertyByName:function(a){return this[a]}})})(window);
(function(){me.Tile=me.Rect.extend({tileId:null,init:function(a,c,b,d,e){this.parent(new me.Vector2d(a*b,c*d),b,d);this.col=a;this.row=c;this.tileId=e;this.flipX=0!==(this.tileId&2147483648);this.flipY=0!==(this.tileId&1073741824);this.flipAD=0!==(this.tileId&536870912);this.flipped=this.flipX||this.flipY||this.flipAD;this.tileId&=536870911}});me.Tileset=Object.extend({init:function(a,c,b,d,e,g){this.name=a;this.tilewidth=c;this.tileheight=b;this.spacing=d;this.margin=e;(this.image=g?me.loader.getImage(me.utils.getBasename(g)):
null)||console.log("melonJS: '"+g+"' file for tileset '"+this.name+"' not found!");this.type={SOLID:"solid",PLATFORM:"platform",L_SLOPE:"lslope",R_SLOPE:"rslope",LADDER:"ladder",BREAKABLE:"breakable"};this.TileProperties=[];this.tileXOffset=[];this.tileYOffset=[];this.image&&(this.hTileCount=~~((this.image.width-this.margin)/(this.tilewidth+this.spacing)),this.vTileCount=~~((this.image.height-this.margin)/(this.tileheight+this.spacing)))},getPropertyList:function(){return{isCollidable:!1,isSolid:!1,
isPlatform:!1,isSlope:!1,isLeftSlope:!1,isRightSlope:!1,isLadder:!1,isBreakable:!1}},getTileProperties:function(a){return this.TileProperties[a]},isTileCollidable:function(a){return this.TileProperties[a].isCollidable},getTileOffsetX:function(a){null==this.tileXOffset[a]&&(this.tileXOffset[a]=this.margin+(this.spacing+this.tilewidth)*(a%this.hTileCount));return this.tileXOffset[a]},getTileOffsetY:function(a){null==this.tileYOffset[a]&&(this.tileYOffset[a]=this.margin+(this.spacing+this.tileheight)*
~~(a/this.hTileCount));return this.tileYOffset[a]}});me.TMXTileset=me.Tileset.extend({init:function(a){this.firstgid=me.XMLParser.getIntAttribute(a,me.TMX_TAG_FIRSTGID);var c=me.XMLParser.getStringAttribute(a,me.TMX_TAG_SOURCE);if(c){c=me.utils.getBasename(c);a=me.loader.getXML(c);if(!a)throw"melonJS:"+c+" TSX tileset not found";me.XMLParser.parseFromString(a);a=me.XMLParser.getFirstElementByTagName("tileset")}this.parent(me.XMLParser.getStringAttribute(a,me.TMX_TAG_NAME),me.XMLParser.getIntAttribute(a,
me.TMX_TAG_TILEWIDTH),me.XMLParser.getIntAttribute(a,me.TMX_TAG_TILEHEIGHT),me.XMLParser.getIntAttribute(a,me.TMX_TAG_SPACING,0),me.XMLParser.getIntAttribute(a,me.TMX_TAG_MARGIN,0),a.getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_SOURCE));this.lastgid=this.firstgid+(this.hTileCount*this.vTileCount-1||0);this.trans=a.getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_TRANS);null!==this.trans&&this.image&&(this.image=me.video.applyRGBFilter(this.image,"transparent",
this.trans.toUpperCase()).canvas);this.tileoffset=new me.Vector2d(0,0);c=a.getElementsByTagName(me.TMX_TAG_TILEOFFSET);0<c.length&&(this.tileoffset.x=me.XMLParser.getIntAttribute(c[0],me.TMX_TAG_X),this.tileoffset.y=me.XMLParser.getIntAttribute(c[0],me.TMX_TAG_Y));a=a.getElementsByTagName(me.TMX_TAG_TILE);for(c=0;c<a.length;c++){var b=me.XMLParser.getIntAttribute(a[c],me.TMX_TAG_ID)+this.firstgid;this.TileProperties[b]={};b=this.TileProperties[b];me.TMXUtils.setTMXProperties(b,a[c]);b.isSolid=b.type?
b.type.toLowerCase()===this.type.SOLID:!1;b.isPlatform=b.type?b.type.toLowerCase()===this.type.PLATFORM:!1;b.isLeftSlope=b.type?b.type.toLowerCase()===this.type.L_SLOPE:!1;b.isRightSlope=b.type?b.type.toLowerCase()===this.type.R_SLOPE:!1;b.isBreakable=b.type?b.type.toLowerCase()===this.type.BREAKABLE:!1;b.isLadder=b.type?b.type.toLowerCase()===this.type.LADDER:!1;b.isSlope=b.isLeftSlope||b.isRightSlope;b.isCollidable=b.isSolid||b.isPlatform||b.isSlope||b.isLadder||b.isBreakable}},contains:function(a){return a>=
this.firstgid&&a<=this.lastgid},getTileImage:function(a){var c=me.video.createCanvasSurface(this.tilewidth,this.tileheight);this.drawTile(c,0,0,a);return c.canvas},drawTile:function(a,c,b,d){if(d.flipped){var e=1,g=0,f=0,i=1,m=c,l=b,c=b=0;a.save();d.flipAD&&(e=0,f=g=1,i=0,l+=this.tileheight-this.tilewidth);d.flipX&&(e=-e,f=-f,m+=d.flipAD?this.tileheight:this.tilewidth);d.flipY&&(g=-g,i=-i,l+=d.flipAD?this.tilewidth:this.tileheight);a.transform(e,g,f,i,m,l)}e=d.tileId-this.firstgid;a.drawImage(this.image,
this.getTileOffsetX(e),this.getTileOffsetY(e),this.tilewidth,this.tileheight,c,b,this.tilewidth,this.tileheight);d.flipped&&a.restore()}});me.TMXTilesetGroup=Object.extend({init:function(){this.tilesets=[]},add:function(a){this.tilesets.push(a)},getTilesetByIndex:function(a){return this.tilesets[a]},getTilesetByGid:function(a){for(var c=-1,b=0,d=this.tilesets.length;b<d;b++){if(this.tilesets[b].contains(a))return this.tilesets[b];this.tilesets[b].firstgid==this.tilesets[b].lastgid&&a>=this.tilesets[b].firstgid&&
(c=b)}if(-1!=c)return this.tilesets[c];throw"no matching tileset found for gid "+a;}})})(window);
(function(){me.TMXOrthogonalRenderer=Object.extend({init:function(a,c,b,d){this.width=a;this.height=c;this.tilewidth=b;this.tileheight=d},pixelToTileCoords:function(a,c){return new me.Vector2d(a/this.tilewidth,c/this.tileheight)},tileToPixelCoords:function(a,c){return new me.Vector2d(a*this.tilewidth,c*this.tileheight)},drawTile:function(a,c,b,d,e){e.drawTile(a,e.tileoffset.x+c*this.tilewidth,e.tileoffset.y+(b+1)*this.tileheight-e.tileheight,d)},drawTileLayer:function(a,c,b,d){var e=this.pixelToTileCoords(b.x+
d.pos.x,b.y+d.pos.y).floorSelf(),b=this.pixelToTileCoords(b.x+d.pos.x+d.width+this.tilewidth,b.y+d.pos.y+d.height+this.tileheight).ceilSelf();b.x=b.x>this.width?this.width:b.x;b.y=b.y>this.height?this.height:b.y;for(d=e.y;d<b.y;d++)for(var g=e.x;g<b.x;g++){var f=c.layerData[g][d];f&&(c.tileset.contains(f.tileId)||(c.tileset=c.tilesets.getTilesetByGid(f.tileId)),this.drawTile(a,g,d,f,c.tileset))}}});me.TMXIsometricRenderer=Object.extend({init:function(a,c,b,d){this.width=a;this.height=c;this.tilewidth=
b;this.tileheight=d;this.hTilewidth=b/2;this.hTileheight=d/2;this.ratio=this.tilewidth/this.tileheight;this.originX=this.height*this.hTilewidth},pixelToTileCoords:function(a,c){a-=this.originX;return new me.Vector2d((c+a/this.ratio)/this.tileheight,(c-a/this.ratio)/this.tileheight)},tileToPixelCoords:function(a,c){return new me.Vector2d((a-c)*this.hTilewidth+this.originX,(a+c)*this.hTileheight)},drawTile:function(a,c,b,d,e){e.drawTile(a,(this.width-1)*e.tilewidth+(c-b)*e.tilewidth>>1,-e.tilewidth+
(c+b)*e.tileheight>>2,d)},drawTileLayer:function(a,c,b,d){var e=c.tileset,g=e.tileoffset,f=this.pixelToTileCoords(b.x+d.pos.x-e.tilewidth,b.y+d.pos.y-e.tileheight).floorSelf(),i=this.pixelToTileCoords(b.x+d.pos.x+d.width+e.tilewidth,b.y+d.pos.y+d.height+e.tileheight).ceilSelf(),i=this.tileToPixelCoords(i.x,i.y),m=this.tileToPixelCoords(f.x,f.y);m.x-=this.hTilewidth;m.y+=this.tileheight;var l=m.y-d.pos.y+b.y>this.hTileheight,b=d.pos.x+b.x-m.x<this.hTilewidth;l&&(b?(f.x--,m.x-=this.hTilewidth):(f.y--,
m.x+=this.hTilewidth),m.y-=this.hTileheight);b^=l;d=f.clone();for(l=m.y;l-this.tileheight<i.y;l+=this.hTileheight){d.setV(f);for(var j=m.x;j<i.x;j+=this.tilewidth){if(0<=d.x&&0<=d.y&&d.x<this.width&&d.y<this.height){var n=c.layerData[d.x][d.y];n&&(e.contains(n.tileId)||(e=c.tileset=c.tilesets.getTilesetByGid(n.tileId),g=e.tileoffset),e.drawTile(a,g.x+j,g.y+l-e.tileheight,n))}d.x++;d.y--}b?(f.y++,m.x-=this.hTilewidth,b=!1):(f.x++,m.x+=this.hTilewidth,b=!0)}}})})(window);
(function(a,c){me.ColorLayer=Object.extend({init:function(a,c,e){this.name=a;this.color=me.utils.HexToRGB(c);this.z=e;this.visible=!0;this.opacity=1;this.floating=!0},reset:function(){},getOpacity:function(){return this.opacity},setOpacity:function(a){a&&(this.opacity=a.clamp(0,1))},update:function(){return!1},draw:function(a,c){var e=a.globalAlpha;a.globalAlpha=this.opacity;a.fillStyle=this.color;a.fillRect(c.left,c.top,c.width,c.height);a.globalAlpha=e}});me.ImageLayer=Object.extend({init:function(a,
d,e,g,f,i){this.name=a;(this.image=g?me.loader.getImage(me.utils.getBasename(g)):null)||console.log("melonJS: '"+g+"' file for Image Layer '"+this.name+"' not found!");this.imagewidth=this.image.width;this.imageheight=this.image.height;this.z=f;this.ratio=i||1;this.lastpos=c.viewport.pos.clone();this.offset=new me.Vector2d(0,0);this.width=d?Math.min(c.viewport.width,d):c.viewport.width;this.height=e?Math.min(c.viewport.height,e):c.viewport.height;this.visible=!0;this.opacity=1;this.floating=!0},reset:function(){this.offset=
this.viewport=this.lastpos=this.image=null},getOpacity:function(){return this.opacity},setOpacity:function(a){a&&(this.opacity=a.clamp(0,1))},update:function(){if(0!==this.ratio){var a=c.viewport.pos;if(!this.lastpos.equals(a))return this.offset.x=(this.imagewidth+this.offset.x+(a.x-this.lastpos.x)*this.ratio)%this.imagewidth,this.offset.y=(this.imageheight+this.offset.y+(a.y-this.lastpos.y)*this.ratio)%this.imageheight,this.lastpos.setV(a),!0}return!1},draw:function(a,c){if(1>this.opacity){var e=
a.globalAlpha;a.globalAlpha=this.opacity}if(0===this.ratio)l=Math.min(c.width,this.imagewidth),j=Math.min(c.height,this.imageheight),a.drawImage(this.image,c.left,c.top,l,j,c.left,c.top,l,j);else{var g=~~this.offset.x,f=~~this.offset.y,i=0,m=0,l=Math.min(this.imagewidth-~~this.offset.x,this.width),j=Math.min(this.imageheight-~~this.offset.y,this.height);do{do a.drawImage(this.image,g,f,l,j,i,m,l,j),f=0,m+=j,j=Math.min(this.imageheight,this.height-m);while(m<this.height);i+=l;if(i>=this.width)break;
g=0;l=Math.min(this.imagewidth,this.width-i);f=~~this.offset.y;m=0;j=Math.min(this.imageheight-~~this.offset.y,this.height)}while(1)}1>this.opacity&&(a.globalAlpha=e)}});CollisionTiledLayer=Object.extend({init:function(a,c){this.realwidth=a;this.realheight=c;this.isCollisionMap=!0},reset:function(){},checkCollision:function(a,c){var e=0>c.x?a.left+c.x:a.right+c.x,g=0>c.y?a.top+c.y:a.bottom+c.y,f={x:0,y:0,xprop:{},yprop:{}};if(0>=e||e>=this.realwidth)f.x=c.x;if(0>=g||g>=this.realheight)f.y=c.y;return f}});
me.TiledLayer=Object.extend({init:function(a,c,e,g,f,i){this.width=a;this.height=c;this.tilewidth=e;this.tileheight=g;this.realwidth=this.width*this.tilewidth;this.realheight=this.height*this.tileheight;this.z=i;this.name=null;this.visible=!1;this.opacity=1;this.layerData=null;this.tileset=(this.tilesets=f)?this.tilesets.getTilesetByIndex(0):null},reset:function(){this.tilesets=this.tileset=this.layerData=null},initArray:function(){this.layerData=[];for(var a=0;a<this.width;a++){this.layerData[a]=
[];for(var c=0;c<this.height;c++)this.layerData[a][c]=null}},getOpacity:function(){return this.opacity},setOpacity:function(a){a&&(this.opacity=a.clamp(0,1))},getTileId:function(a,c){var e=this.getTile(a,c);return e?e.tileId:null},getTile:function(a,c){return this.layerData[~~(a/this.tilewidth)][~~(c/this.tileheight)]},setTile:function(a,c,e){this.layerData[a][c]=new me.Tile(a,c,this.tilewidth,this.tileheight,e)},clearTile:function(a,c){this.layerData[a][c]=null},checkCollision:function(a,c){var e=
0>c.x?~~(a.left+c.x):Math.ceil(a.right-1+c.x),g=0>c.y?~~(a.top+c.y):Math.ceil(a.bottom-1+c.y),f={x:0,xtile:void 0,xprop:{},y:0,ytile:void 0,yprop:{}};0>=e||e>=this.realwidth?f.x=c.x:0!=c.x&&(f.xtile=this.getTile(e,Math.ceil(a.bottom-1)),f.xtile&&this.tileset.isTileCollidable(f.xtile.tileId)?(f.x=c.x,f.xprop=this.tileset.getTileProperties(f.xtile.tileId)):(f.xtile=this.getTile(e,~~a.top),f.xtile&&this.tileset.isTileCollidable(f.xtile.tileId)&&(f.x=c.x,f.xprop=this.tileset.getTileProperties(f.xtile.tileId))));
0!=c.y&&(f.ytile=this.getTile(0>c.x?~~a.left:Math.ceil(a.right-1),g),f.ytile&&this.tileset.isTileCollidable(f.ytile.tileId)?(f.y=c.y||1,f.yprop=this.tileset.getTileProperties(f.ytile.tileId)):(f.ytile=this.getTile(0>c.x?Math.ceil(a.right-1):~~a.left,g),f.ytile&&this.tileset.isTileCollidable(f.ytile.tileId)&&(f.y=c.y||1,f.yprop=this.tileset.getTileProperties(f.ytile.tileId))));return f},update:function(){return!1}});me.TMXLayer=me.TiledLayer.extend({init:function(a,c,e,g,f,i){this.parent(me.XMLParser.getIntAttribute(a,
me.TMX_TAG_WIDTH),me.XMLParser.getIntAttribute(a,me.TMX_TAG_HEIGHT),c,e,f,i);this.orientation=g;this.name=me.XMLParser.getStringAttribute(a,me.TMX_TAG_NAME);this.visible=1==me.XMLParser.getIntAttribute(a,me.TMX_TAG_VISIBLE,1);this.opacity=me.XMLParser.getFloatAttribute(a,me.TMX_TAG_OPACITY,1).clamp(0,1);me.TMXUtils.setTMXProperties(this,a);void 0===this.preRender&&(this.preRender=me.sys.preRender);if((this.isCollisionMap=this.name.toLowerCase().contains(me.LevelConstants.COLLISION_MAP))&&!me.debug.renderCollisionMap)this.visible=
!1;a=a.getElementsByTagName(me.TMX_TAG_DATA)[0];c=me.XMLParser.getStringAttribute(a,me.TMX_TAG_ENCODING,null);e=me.XMLParser.getStringAttribute(a,me.TMX_TAG_COMPRESSION,null);""==c&&(c=null);""==e&&(e=null);if(this.visible){switch(this.orientation){case "orthogonal":this.renderer=new me.TMXOrthogonalRenderer(this.width,this.height,this.tilewidth,this.tileheight);break;case "isometric":this.renderer=new me.TMXIsometricRenderer(this.width,this.height,this.tilewidth,this.tileheight);break;default:throw"melonJS: "+
this.orientation+" type TMX Tile Map not supported!";}this.preRender&&(this.layerSurface=me.video.createCanvasSurface(this.width*this.tilewidth,this.height*this.tileheight),this.layerCanvas=this.layerSurface.canvas,this.layerSurface.globalAlpha=this.opacity)}if(this.visible||this.isCollisionMap)this.initArray(),this.fillArray(a,c,e)},reset:function(){this.preRender&&(this.layerSurface=this.layerCanvas=null);this.renderer=null;this.parent()},fillArray:function(a,c,e){switch(e){case null:switch(c){case null:a=
a.getElementsByTagName(me.TMX_TAG_TILE);break;case me.TMX_TAG_CSV:case me.TMX_TAG_ATTR_BASE64:for(var e="",g=0,f=a.childNodes.length;g<f;g++)e+=a.childNodes[g].nodeValue;a=c==me.TMX_TAG_ATTR_BASE64?me.utils.decodeBase64AsArray(e,4):me.utils.decodeCSV(e,this.width);break;default:throw"melonJS: TMX Tile Map "+c+" encoding not supported!";}break;default:throw"melonJS: "+e+" compressed TMX Tile Map not supported!";}for(g=e=0;g<this.height;g++)for(f=0;f<this.width;f++){var i=null==c?me.XMLParser.getIntAttribute(a[e++],
me.TMX_TAG_GID):a[e++];0!==i&&(i=new me.Tile(f,g,this.tilewidth,this.tileheight,i),this.layerData[f][g]=i,this.tileset.contains(i.tileId)||(this.tileset=this.tilesets.getTilesetByGid(i.tileId)),this.visible&&this.preRender&&this.renderer.drawTile(this.layerSurface,f,g,i,this.tileset))}},clearTile:function(a,c){this.parent(a,c);this.visible&&this.preRender&&this.layerSurface.clearRect(a*this.tilewidth,c*this.tileheight,this.tilewidth,this.tileheight)},setOpacity:function(a){this.parent(a);this.preRender&&
(this.layerSurface.globalAlpha=this.opacity)},draw:function(a,d){var e=c.viewport.pos;if(this.preRender){var g=Math.min(d.width,this.realwidth),f=Math.min(d.height,this.realheight);a.drawImage(this.layerCanvas,e.x+d.pos.x,e.y+d.pos.y,g,f,d.pos.x,d.pos.y,g,f)}else g=a.globalAlpha,a.globalAlpha=this.opacity,this.renderer.drawTileLayer(a,this,e,d),a.globalAlpha=g}})})(window,me.game);
(function(){me.TileMap=Object.extend({init:function(a,c){this.pos=new me.Vector2d(a,c);this.z=0;this.name=null;this.height=this.width=0;this.realheight=this.realwidth=-1;this.tileheight=this.tilewidth=0;this.tilesets=null;this.mapLayers=[];this.objectGroups=[];this.initialized=!1},reset:function(){this.tilesets=null;this.mapLayers.length=0;this.objectGroups.length=0;this.pos.set(0,0);this.initialized=!1},getObjectGroupByName:function(a){return this.objectGroups[a]},getObjectGroups:function(){return this.objectGroups},
getLayers:function(){return this.mapLayers},getLayerByName:function(a){for(var c=null,a=a.trim().toLowerCase(),b=this.mapLayers.length;b--;)if(this.mapLayers[b].name.toLowerCase().contains(a)){c=this.mapLayers[b];break}a.toLowerCase().contains(me.LevelConstants.COLLISION_MAP)&&null==c&&(c=new CollisionTiledLayer(me.game.currentLevel.realwidth,me.game.currentLevel.realheight));return c},clearTile:function(a,c){for(var b=this.mapLayers.length;b--;)this.mapLayers[b].visible&&this.mapLayers[b]instanceof
me.TiledLayer&&this.mapLayers[b].clearTile(a,c)}});me.TMXTileMap=me.TileMap.extend({init:function(a,c,b){this.parent(c,b);this.xmlMap=me.loader.getXML(a);if(!this.xmlMap)throw"melonJS:"+a+" TMX map not found";this.orientation=this.version="";this.tilesets=null},reset:function(){if(!0===this.initialized){for(var a=this.mapLayers.length;a--;)this.mapLayers[a].reset(),this.mapLayers[a]=null;for(a=this.objectGroups.length;a--;)this.objectGroups[a].reset(),this.objectGroups[a]=null;this.parent();this.initialized=
!1}},load:function(){if(!this.initialized){var a=0,c=0.25;me.XMLParser.parseFromString(this.xmlMap);for(var b=me.XMLParser.getAllTagElements(),d=0;d<b.length;d++)switch(b.item(d).nodeName){case me.TMX_TAG_MAP:var e=b.item(d);this.version=me.XMLParser.getStringAttribute(e,me.TMX_TAG_VERSION);this.orientation=me.XMLParser.getStringAttribute(e,me.TMX_TAG_ORIENTATION);this.width=me.XMLParser.getIntAttribute(e,me.TMX_TAG_WIDTH);this.height=me.XMLParser.getIntAttribute(e,me.TMX_TAG_HEIGHT);this.tilewidth=
me.XMLParser.getIntAttribute(e,me.TMX_TAG_TILEWIDTH);this.tileheight=me.XMLParser.getIntAttribute(e,me.TMX_TAG_TILEHEIGHT);this.realwidth=this.width*this.tilewidth;this.realheight=this.height*this.tileheight;this.backgroundcolor=me.XMLParser.getStringAttribute(e,me.TMX_BACKGROUND_COLOR);this.z=a++;if(this.realwidth<me.game.viewport.width||this.realheight<me.game.viewport.height){var g=~~((me.game.viewport.width-this.realwidth)/2),f=~~((me.game.viewport.height-this.realheight)/2);this.pos.add({x:0<
g?g:0,y:0<f?f:0})}me.TMXUtils.setTMXProperties(this,e);(this.background_color=this.backgroundcolor?this.backgroundcolor:this.background_color)&&this.mapLayers.push(new me.ColorLayer("background_color",this.background_color,a++));this.background_image&&this.mapLayers.push(new me.ImageLayer("background_image",this.width,this.height,this.background_image,a++));break;case me.TMX_TAG_TILESET:this.tilesets||(this.tilesets=new me.TMXTilesetGroup);this.tilesets.add(new me.TMXTileset(b.item(d)));break;case me.TMX_TAG_IMAGE_LAYER:var f=
me.XMLParser.getStringAttribute(b.item(d),me.TMX_TAG_NAME),e=me.XMLParser.getIntAttribute(b.item(d),me.TMX_TAG_WIDTH),g=me.XMLParser.getIntAttribute(b.item(d),me.TMX_TAG_HEIGHT),i=b.item(d).getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_SOURCE),e=new me.ImageLayer(f,e*this.tilewidth,g*this.tileheight,i,a++);e.visible=1==me.XMLParser.getIntAttribute(b.item(d),me.TMX_TAG_VISIBLE,1);e.opacity=me.XMLParser.getFloatAttribute(b.item(d),me.TMX_TAG_OPACITY,1);me.TMXUtils.setTMXProperties(e,
b.item(d));this.mapLayers.push(e);break;case me.TMX_TAG_LAYER:i=me.XMLParser.getStringAttribute(b.item(d),me.TMX_TAG_NAME);i.toLowerCase().contains(me.LevelConstants.PARALLAX_MAP)?(e=me.XMLParser.getIntAttribute(b.item(d),me.TMX_TAG_WIDTH),g=me.XMLParser.getIntAttribute(b.item(d),me.TMX_TAG_HEIGHT),f={},me.TMXUtils.setTMXProperties(f,b.item(d)),f.ratio&&(c=f.ratio),e=new me.ImageLayer(i,e*this.tilewidth,g*this.tileheight,f.imagesrc,a++,c),e.visible=1==me.XMLParser.getIntAttribute(b.item(d),me.TMX_TAG_VISIBLE,
1),e.opacity=me.XMLParser.getFloatAttribute(b.item(d),me.TMX_TAG_OPACITY,1),me.TMXUtils.mergeProperties(e,f,!1),c+=c*c,this.mapLayers.push(e)):this.mapLayers.push(new me.TMXLayer(b.item(d),this.tilewidth,this.tileheight,this.orientation,this.tilesets,a++));break;case me.TMX_TAG_OBJECTGROUP:e=me.XMLParser.getStringAttribute(b.item(d),me.TMX_TAG_NAME),this.objectGroups.push(new me.TMXOBjectGroup(e,b.item(d),this.tilesets,a++))}me.XMLParser.free();this.initialized=!0}}})})(window);
(function(){var a=me,c={},b={},d=[],e=0;c.reset=function(){};c.addLevel=function(){throw"melonJS: no level loader defined";};c.addTMXLevel=function(a,c){if(null==b[a])b[a]=new me.TMXTileMap(a,0,0),b[a].name=a,d[d.length]=a;else return!1;c&&c();return!0};c.loadLevel=function(a){a=a.toString().toLowerCase();if(void 0===b[a])throw"melonJS: level "+a+" not found";if(b[a]instanceof me.TMXTileMap){var f=me.state.isRunning();f&&me.state.pause();me.game.reset();me.utils.resetGUID(a);b[c.getCurrentLevelId()]&&
b[c.getCurrentLevelId()].reset();b[a].load();e=d.indexOf(a);me.game.loadTMXLevel(b[a]);f&&me.state.resume()}else throw"melonJS: no level loader defined";return!0};c.getCurrentLevelId=function(){return d[e]};c.reloadLevel=function(){return c.loadLevel(c.getCurrentLevelId())};c.nextLevel=function(){return e+1<d.length?c.loadLevel(d[e+1]):!1};c.previousLevel=function(){return 0<=e-1?c.loadLevel(d[e-1]):!1};a.levelDirector=c})(window);
(function(){me.Tween=function(a){var c={},b={},d={},e=1E3,g=0,f=null,i=0,m=me.Tween.Easing.Linear.EaseNone,l=null,j=null,n=null;this.to=function(b,c){null!==c&&(e=c);for(var f in b)null!==a[f]&&(d[f]=b[f]);return this};this.start=function(){me.game.add(this,999);f=me.timer.getTime()+g;i=0;for(var e in d)null!==a[e]&&(c[e]=a[e],b[e]=d[e]-a[e]);return this};this.stop=function(){me.game.remove(this);return this};this.delay=function(a){g=a;return this};me.event.subscribe(me.event.STATE_PAUSE,function(){f&&
(i=me.timer.getTime())});me.event.subscribe(me.event.STATE_RESUME,function(){f&&i&&(f+=me.timer.getTime()-i)});this.easing=function(a){m=a;return this};this.chain=function(a){l=a;return this};this.onUpdate=function(a){j=a;return this};this.onComplete=function(a){n=a;return this};this.update=function(){var d,g,i;g=me.timer.getTime();if(g<f)return!0;if(1<=(g=(g-f)/e))g=1;i=m(g);for(d in b)a[d]=c[d]+b[d]*i;null!==j&&j.call(a,i);return 1===g?(me.game.remove(this),null!==n&&n.call(a),null!==l&&l.start(),
!1):!0};this.destroy=function(){return!0}};me.Tween.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{}};me.Tween.Easing.Linear.EaseNone=function(a){return a};me.Tween.Easing.Quadratic.EaseIn=function(a){return a*a};me.Tween.Easing.Quadratic.EaseOut=function(a){return a*(2-a)};me.Tween.Easing.Quadratic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a:-0.5*(--a*(a-2)-1)};me.Tween.Easing.Cubic.EaseIn=function(a){return a*a*
a};me.Tween.Easing.Cubic.EaseOut=function(a){return--a*a*a+1};me.Tween.Easing.Cubic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*a:0.5*((a-=2)*a*a+2)};me.Tween.Easing.Quartic.EaseIn=function(a){return a*a*a*a};me.Tween.Easing.Quartic.EaseOut=function(a){return 1- --a*a*a*a};me.Tween.Easing.Quartic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*a*a:-0.5*((a-=2)*a*a*a-2)};me.Tween.Easing.Quintic.EaseIn=function(a){return a*a*a*a*a};me.Tween.Easing.Quintic.EaseOut=function(a){return--a*a*a*a*a+1};me.Tween.Easing.Quintic.EaseInOut=
function(a){return 1>(a*=2)?0.5*a*a*a*a*a:0.5*((a-=2)*a*a*a*a+2)};me.Tween.Easing.Sinusoidal.EaseIn=function(a){return 1-Math.cos(a*Math.PI/2)};me.Tween.Easing.Sinusoidal.EaseOut=function(a){return Math.sin(a*Math.PI/2)};me.Tween.Easing.Sinusoidal.EaseInOut=function(a){return 0.5*(1-Math.cos(Math.PI*a))};me.Tween.Easing.Exponential.EaseIn=function(a){return 0===a?0:Math.pow(1024,a-1)};me.Tween.Easing.Exponential.EaseOut=function(a){return 1===a?1:1-Math.pow(2,-10*a)};me.Tween.Easing.Exponential.EaseInOut=
function(a){return 0===a?0:1===a?1:1>(a*=2)?0.5*Math.pow(1024,a-1):0.5*(-Math.pow(2,-10*(a-1))+2)};me.Tween.Easing.Circular.EaseIn=function(a){return 1-Math.sqrt(1-a*a)};me.Tween.Easing.Circular.EaseOut=function(a){return Math.sqrt(1- --a*a)};me.Tween.Easing.Circular.EaseInOut=function(a){return 1>(a*=2)?-0.5*(Math.sqrt(1-a*a)-1):0.5*(Math.sqrt(1-(a-=2)*a)+1)};me.Tween.Easing.Elastic.EaseIn=function(a){var c,b=0.1;if(0===a)return 0;if(1===a)return 1;!b||1>b?(b=1,c=0.1):c=0.4*Math.asin(1/b)/(2*Math.PI);
return-(b*Math.pow(2,10*(a-=1))*Math.sin((a-c)*2*Math.PI/0.4))};me.Tween.Easing.Elastic.EaseOut=function(a){var c,b=0.1;if(0===a)return 0;if(1===a)return 1;!b||1>b?(b=1,c=0.1):c=0.4*Math.asin(1/b)/(2*Math.PI);return b*Math.pow(2,-10*a)*Math.sin((a-c)*2*Math.PI/0.4)+1};me.Tween.Easing.Elastic.EaseInOut=function(a){var c,b=0.1;if(0===a)return 0;if(1===a)return 1;!b||1>b?(b=1,c=0.1):c=0.4*Math.asin(1/b)/(2*Math.PI);return 1>(a*=2)?-0.5*b*Math.pow(2,10*(a-=1))*Math.sin((a-c)*2*Math.PI/0.4):0.5*b*Math.pow(2,
-10*(a-=1))*Math.sin((a-c)*2*Math.PI/0.4)+1};me.Tween.Easing.Back.EaseIn=function(a){return a*a*(2.70158*a-1.70158)};me.Tween.Easing.Back.EaseOut=function(a){return--a*a*(2.70158*a+1.70158)+1};me.Tween.Easing.Back.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*(3.5949095*a-2.5949095):0.5*((a-=2)*a*(3.5949095*a+2.5949095)+2)};me.Tween.Easing.Bounce.EaseIn=function(a){return 1-me.Tween.Easing.Bounce.EaseOut(1-a)};me.Tween.Easing.Bounce.EaseOut=function(a){return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=
1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375};me.Tween.Easing.Bounce.EaseInOut=function(a){return 0.5>a?0.5*me.Tween.Easing.Bounce.EaseIn(2*a):0.5*me.Tween.Easing.Bounce.EaseOut(2*a-1)+0.5}})();
(function(){var a=me,c={},b={};c.STATE_PAUSE="me.state.onPause";c.STATE_RESUME="me.state.onResume";c.GAME_INIT="me.game.onInit";c.LEVEL_LOADED="me.game.onLevelLoaded";c.LOADER_COMPLETE="me.loader.onload";c.LOADER_PROGRESS="me.loader.onProgress";c.KEYDOWN="me.input.keydown";c.KEYUP="me.input.keyup";c.WINDOW_ONRESIZE="window.onresize";c.publish=function(a,c){for(var g=b[a],f=g?g.length:0;f--;)g[f].apply(window,c||[])};c.subscribe=function(a,c){b[a]||(b[a]=[]);b[a].push(c);return[a,c]};c.unsubscribe=
function(a,c){for(var g=b[c?a:a[0]],c=c||a[1],f=g?g.length:0;f--;)g[f]===c&&g.splice(f,1)};a.event=c})();
(function(){var a=me,c={};c.Base=Object.extend({version:void 0,init:function(){}});c.patch=function(a,c,e){void 0!==a.prototype&&(a=a.prototype);if("function"==typeof a[c]){var g=a[c];a[c]=function(){var a=this.parent;this.parent=g;var b=e.apply(this,arguments);this.parent=a;return b}}else console.error(c+" is not an existing function")};c.register=function(a,c){me.plugin[c]&&console.error("plugin "+c+" already registered");if(void 0===a.prototype.version)throw"melonJS: Plugin version not defined !";
if(0<me.sys.checkVersion(a.prototype.version))throw"melonJS: Plugin version mismatch, expected: "+a.prototype.version+", got: "+me.version;me.plugin[c]=new a;if(!(me.plugin[c]instanceof me.plugin.Base))throw"melonJS: Plugin should extend the me.plugin.Base Class !";};a.plugin=c})();
